import type { Card } from "./study-data";

export const dataEngineeringCards: Card[] = [
  {
    id: "de-etl-vs-elt",
    category: "Data engineering",
    question: "ETL vs ELT: how do you choose?",
    answer: "ETL transforms data before loading, which can reduce exposure and enforce a strict target contract before data reaches the platform. ELT loads raw or lightly processed data first and uses warehouse or lakehouse compute for transformation, improving replayability and iteration. Choose based on privacy constraints, source volume, target compute, latency, governance and whether raw history must be retained—not by acronym preference.",
    signals: ["Transform location", "Replayability", "Governance", "Compute economics"],
    trap: "Claiming ELT is always modern and ignoring sensitive-data minimization or target-system limits.",
    followUp: "Where would you tokenize or remove PII in an ELT architecture?",
    priority: "Core",
  },
  {
    id: "de-batch-vs-streaming",
    category: "Data engineering",
    question: "When should a pipeline be batch rather than streaming?",
    answer: "Use batch when the business can tolerate periodic freshness, inputs arrive in bounded files, recomputation is valuable and simpler operations outweigh lower latency. Use streaming when decisions genuinely depend on continuous updates and the team can support event-time handling, state, replay and stronger observability. Often the right design is a streaming ingestion layer with scheduled downstream materialization.",
    signals: ["Business latency", "Operational complexity", "Replay", "Hybrid design"],
    trap: "Choosing streaming because it sounds scalable without a freshness requirement that justifies it.",
    followUp: "What evidence would justify migrating a reliable hourly batch job to streaming?",
    priority: "Core",
  },
  {
    id: "de-event-time-watermarks",
    category: "Data engineering",
    question: "Explain event time, processing time and watermarks.",
    answer: "Event time is when an event occurred at the source; processing time is when the platform handled it. Because events arrive late or out of order, a watermark estimates how complete event-time data is and lets the system close windows while accepting a defined lateness bound. The policy must specify how later events update results, are quarantined or trigger correction jobs.",
    signals: ["Out-of-order events", "Completeness estimate", "Allowed lateness", "Corrections"],
    trap: "Treating a watermark as proof that no earlier event can arrive afterward.",
    followUp: "How would a seven-day-late purchase affect a daily revenue aggregate already published?",
    priority: "Build",
  },
  {
    id: "de-idempotent-pipelines",
    category: "Data engineering",
    question: "How do you make a data pipeline idempotent?",
    answer: "Give records stable business or event keys, make writes deterministic, and use merge, upsert or partition-replacement semantics so replaying the same input produces the same target state. Track input versions and checkpoints, separate side effects from computation, and commit outputs atomically. Idempotency must cover the complete unit of work, not only one transformation function.",
    signals: ["Stable keys", "Deterministic writes", "Atomic commit", "Replay"],
    trap: "Relying only on retry counts while duplicate writes and external side effects remain possible.",
    followUp: "How would you make a pipeline idempotent when the source has no reliable primary key?",
    priority: "Core",
  },
  {
    id: "de-exactly-once",
    category: "Data engineering",
    question: "What does exactly-once processing really mean?",
    answer: "Exactly-once is an end-to-end outcome, not simply a broker setting. It usually combines replayable input, coordinated checkpoints or transactions, deterministic processing and an idempotent or transactional sink so each logical event affects final state once despite retries. External side effects can break the guarantee, so state the boundary and failure assumptions explicitly.",
    signals: ["End-to-end boundary", "Checkpointing", "Transactional sink", "Failure assumptions"],
    trap: "Equating Kafka's delivery configuration with exactly-once business results in every downstream system.",
    followUp: "Can you promise exactly-once behavior when the sink is a third-party REST API?",
    priority: "Advanced",
  },
  {
    id: "de-backfill-design",
    category: "Data engineering",
    question: "How would you run a safe large historical backfill?",
    answer: "Freeze the transformation and source snapshot or version, define the affected partitions, estimate load, and write through the same validated contract as the regular pipeline. Use bounded chunks, isolated compute and checkpoints; compare counts, checksums and business metrics; then publish atomically. Protect current workloads and define how concurrent new data will be reconciled.",
    signals: ["Versioned inputs", "Bounded chunks", "Validation", "Atomic publish"],
    trap: "Launching one giant rerun against production tables without capacity limits or reconciliation.",
    followUp: "How would you handle records updated by the live pipeline while the backfill is running?",
    priority: "Build",
  },
  {
    id: "de-cdc",
    category: "Data engineering",
    question: "How does change data capture work, and what can go wrong?",
    answer: "CDC reads database changes—preferably from the transaction log—and emits ordered inserts, updates and deletes with source positions. Consumers apply them to downstream state and persist checkpoints. Key risks include snapshot-to-log gaps, duplicate delivery, schema changes, transaction ordering, tombstones, long-running transactions and log retention expiring before recovery.",
    signals: ["Transaction log", "Source position", "Snapshot handoff", "Deletes"],
    trap: "Describing CDC as periodic updated_at polling and ignoring deletes or ordering.",
    followUp: "How would you take the initial snapshot without missing changes committed during the copy?",
    priority: "Core",
  },
  {
    id: "de-kafka-partitions",
    category: "Data engineering",
    question: "How do Kafka partitions and consumer groups affect scale and ordering?",
    answer: "A topic partition is an ordered append-only log and the unit of parallelism. A record key determines partition placement when key-based ordering matters. Within a consumer group, one partition is assigned to at most one consumer at a time, so useful parallelism is bounded by partition count. More partitions improve throughput but increase coordination, open files and rebalancing cost.",
    signals: ["Partition ordering", "Record key", "Consumer group", "Parallelism limit"],
    trap: "Saying Kafka provides global ordering across a multi-partition topic.",
    followUp: "How would you preserve per-customer order while avoiding a single hot partition?",
    priority: "Core",
  },
  {
    id: "de-schema-evolution",
    category: "Data engineering",
    question: "How do you manage schema evolution in event pipelines?",
    answer: "Use versioned schemas with compatibility rules, validate producers before registration, and make consumers tolerant of additive changes and explicit about breaking ones. Give fields stable meaning, defaults and nullability; retain raw events for replay; monitor unknown or rejected versions; and coordinate migrations when semantics change even if the physical type remains compatible.",
    signals: ["Compatibility mode", "Producer validation", "Consumer migration", "Semantic change"],
    trap: "Assuming adding a nullable field is always safe regardless of consumer behavior or field meaning.",
    followUp: "How would you migrate a field from integer cents to decimal currency values?",
    priority: "Build",
  },
  {
    id: "de-spark-shuffles",
    category: "Data engineering",
    question: "What causes a Spark shuffle, and why is it expensive?",
    answer: "A shuffle redistributes records across partitions for operations such as joins, groupBy, distinct and repartition. It incurs serialization, network transfer, disk spill, sorting and stage boundaries, so it often dominates runtime. Reduce unnecessary shuffles, filter and project early, broadcast genuinely small tables, choose partition keys carefully and inspect the physical plan and task metrics.",
    signals: ["Data redistribution", "Stage boundary", "Spill/network", "Physical plan"],
    trap: "Trying to eliminate every shuffle even when correct global grouping requires one.",
    followUp: "When can a broadcast join make performance worse or crash executors?",
    priority: "Core",
  },
  {
    id: "de-spark-skew",
    category: "Data engineering",
    question: "How do you diagnose and fix data skew in Spark?",
    answer: "Skew appears when a small number of keys create much larger partitions, leaving a few tasks running or spilling long after the rest finish. Confirm it with key-frequency samples and task input, duration and spill distributions. Remedies include filtering pathological keys, pre-aggregation, adaptive skew joins, salting hot keys or processing exceptional keys separately.",
    signals: ["Hot keys", "Task distribution", "Adaptive execution", "Salting"],
    trap: "Adding more executors without changing the oversized partition assigned to one task.",
    followUp: "What correctness risks does key salting introduce during aggregation?",
    priority: "Build",
  },
  {
    id: "de-partitioning-small-files",
    category: "Data engineering",
    question: "How do you choose table partitions and avoid the small-files problem?",
    answer: "Partition on fields frequently used for coarse pruning—often date—while keeping each partition large enough to avoid excessive metadata and file-open overhead. Do not partition on very high-cardinality columns. Control writer parallelism, compact files toward a workload-appropriate size, cluster within partitions when useful and monitor file counts as well as bytes.",
    signals: ["Partition pruning", "Cardinality", "Compaction", "File-size target"],
    trap: "Partitioning by customer ID because queries filter by customer, creating millions of tiny directories or files.",
    followUp: "How would you optimize a table queried by date range and customer ID?",
    priority: "Core",
  },
  {
    id: "de-parquet",
    category: "Data engineering",
    question: "Why is Parquet effective for analytics workloads?",
    answer: "Parquet stores values by column in row groups, enabling column pruning, compression and encoding suited to similar values. Embedded statistics can skip row groups that cannot match a filter. It is less suitable for frequent single-row updates or tiny point reads, and performance still depends on sensible row-group, file, partition and sort layout.",
    signals: ["Columnar layout", "Compression", "Predicate pruning", "Row groups"],
    trap: "Saying Parquet is faster for every access pattern simply because it is columnar.",
    followUp: "Why might a Parquet query still scan most of the table despite selecting two columns?",
    priority: "Core",
  },
  {
    id: "de-scd-type-2",
    category: "Data engineering",
    question: "How do you implement a slowly changing dimension Type 2?",
    answer: "Represent each business entity with multiple effective-dated rows, a surrogate key, valid-from and valid-to timestamps and usually a current flag. On a tracked change, expire the current row and insert the new version in one transaction or deterministic merge. Handle late-arriving corrections, unchanged rows, deletes and overlapping validity intervals explicitly.",
    signals: ["Effective dates", "Surrogate key", "Expire + insert", "Late arrivals"],
    trap: "Overwriting the current row and losing the history that Type 2 is meant to preserve.",
    followUp: "How would you join a historical fact to the dimension version valid at event time?",
    priority: "Core",
  },
  {
    id: "de-star-vs-snowflake",
    category: "Data engineering",
    question: "Star schema vs snowflake schema: what is the tradeoff?",
    answer: "A star schema keeps facts surrounded by relatively denormalized dimensions, simplifying BI queries and often reducing joins. A snowflake normalizes dimension hierarchies, reducing duplication and improving centralized maintenance but increasing join and semantic complexity. Choose based on user tools, scale, ownership and change patterns; neither replaces clear grain and conformed dimensions.",
    signals: ["Fact grain", "Denormalization", "Query simplicity", "Conformed dimensions"],
    trap: "Debating normalization without first defining what one row in the fact table represents.",
    followUp: "How would you model an order containing multiple products and promotions?",
    priority: "Core",
  },
  {
    id: "de-data-quality-contracts",
    category: "Data engineering",
    question: "How would you design data quality checks and data contracts?",
    answer: "Define ownership and machine-checkable expectations for schema, semantics, freshness, completeness, uniqueness, valid ranges and referential integrity at important boundaries. Run cheap checks early and deeper checks before publication, quarantine bad data when possible, route alerts by impact and preserve lineage. Contracts need versioning and an exception process, not only failing assertions.",
    signals: ["Ownership", "Boundary checks", "Quarantine", "Versioned contract"],
    trap: "Creating hundreds of unowned alerts that teams learn to ignore.",
    followUp: "Which failures should block publication versus warn and continue?",
    priority: "Core",
  },
  {
    id: "de-airflow-dag",
    category: "Data engineering",
    question: "What makes an Airflow DAG production-ready?",
    answer: "Tasks should be bounded, idempotent and parameterized by logical data interval; dependencies should reflect data readiness rather than arbitrary sleeps. Configure retries only for transient failures, timeouts, pools and concurrency limits; keep secrets out of code; emit lineage and quality signals; support backfills; and give every failure an owner and runbook.",
    signals: ["Logical interval", "Idempotent tasks", "Concurrency controls", "Operational ownership"],
    trap: "Putting an entire pipeline in one giant Python task or using sensors that consume workers indefinitely.",
    followUp: "How would you prevent a retry from repeating an external side effect?",
    priority: "Build",
  },
  {
    id: "de-lakehouse-transactions",
    category: "Data engineering",
    question: "What does a lakehouse table format add beyond Parquet files?",
    answer: "Formats such as Delta Lake, Iceberg and Hudi add table metadata and transaction semantics over object-store files: atomic commits, snapshots, schema evolution, partition evolution and often row-level merge or delete support. They improve concurrent reads and writes and time travel, but require catalog integration, metadata maintenance and correct retention or compaction policies.",
    signals: ["Table metadata", "Atomic snapshots", "Schema evolution", "Maintenance"],
    trap: "Calling any collection of Parquet files a lakehouse with ACID guarantees.",
    followUp: "What can go wrong if old snapshots or data files are vacuumed too aggressively?",
    priority: "Build",
  },
  {
    id: "de-incremental-late-data",
    category: "Data engineering",
    question: "How do you build an incremental transformation that handles late data?",
    answer: "Track a trustworthy source position or event timestamp, but reprocess an overlap window large enough for expected lateness and merge by stable key rather than append blindly. Record the high-water mark only after successful publication, make the transformation deterministic, and schedule broader reconciliation for events beyond the normal window or corrected source history.",
    signals: ["High-water mark", "Overlap window", "Deterministic merge", "Reconciliation"],
    trap: "Filtering strictly greater than the last timestamp and permanently missing late or tied records.",
    followUp: "How would you choose the overlap window without repeatedly scanning excessive history?",
    priority: "Core",
  },
  {
    id: "de-system-design-event-analytics",
    category: "Data engineering",
    question: "Design a reliable product-event pipeline from applications to analytics tables.",
    answer: "Define event contracts and privacy rules at producers; accept events through a durable, partitioned log; retain raw immutable data for replay; validate and quarantine malformed records; transform with event-time and deduplication semantics; publish modeled warehouse or lakehouse tables; and add lineage, freshness, volume, quality and cost monitoring. Explain backpressure, schema rollout, deletion and regional outage recovery.",
    signals: ["Event contract", "Durable log", "Replayable raw layer", "Operability"],
    trap: "Drawing services without defining delivery guarantees, event identity, late-data policy or who owns broken producers.",
    followUp: "How would you evolve the design from ten thousand to one million events per second?",
    priority: "Build",
  },
];
