import type { Card } from "./study-data";

export const extraCards: Card[] = [
  {
    id: "sql-find-duplicates",
    category: "Python + SQL",
    question: "Write SQL to find duplicate records.",
    answer: "First define the business key that should be unique. Group by those columns and filter groups with COUNT(*) > 1 to identify duplicate keys. To return the actual rows, rank inside each key with ROW_NUMBER and keep rows above one; use a deterministic ordering column to define which record is canonical.",
    signals: ["Business key", "GROUP BY + HAVING", "ROW_NUMBER", "Deterministic survivor"],
    trap: "Using SELECT DISTINCT, which hides duplicate output but does not identify or repair duplicate source rows.",
    followUp: "How would you safely delete duplicates while retaining the newest valid record?",
    priority: "Core",
  },
  {
    id: "python-two-sum",
    category: "Python + SQL",
    question: "Solve Two Sum and explain the tradeoff.",
    answer: "Scan once while storing each previously seen value and its index in a dictionary. For each value x, check whether target - x is already present; if so, return the pair. This is O(n) time and O(n) space, compared with O(n²) brute force or O(n log n) sorting that complicates original indices.",
    signals: ["Complement lookup", "One pass", "O(n) time", "O(n) space"],
    trap: "Inserting the current item before checking and accidentally pairing one element with itself.",
    followUp: "How would the solution change if the input were already sorted?",
    priority: "Core",
  },
  {
    id: "python-valid-parentheses",
    category: "Python + SQL",
    question: "How would you solve Valid Parentheses?",
    answer: "Use a stack of opening brackets. On a closing bracket, fail if the stack is empty or the popped opener does not match. At the end, the stack must be empty. The algorithm is O(n) time and O(n) worst-case space, and an early mismatch can stop immediately.",
    signals: ["Stack", "Matching map", "Early failure", "Final empty check"],
    trap: "Checking only counts, which accepts incorrectly ordered strings such as ([)].",
    followUp: "How would you adapt the parser to ignore brackets inside quoted strings?",
    priority: "Core",
  },
  {
    id: "python-binary-search",
    category: "Python + SQL",
    question: "Implement binary search without an off-by-one bug.",
    answer: "Maintain an explicit invariant over a sorted search interval. With inclusive low and high bounds, loop while low <= high, compute mid safely, compare, then move low to mid + 1 or high to mid - 1. State what is returned when absent and test empty, one-item and boundary cases.",
    signals: ["Sorted input", "Interval invariant", "Boundary updates", "O(log n)"],
    trap: "Updating a bound to mid instead of past mid, which can cause an infinite loop.",
    followUp: "How would you return the first occurrence when duplicate values exist?",
    priority: "Core",
  },
  {
    id: "sql-ranking-functions",
    category: "Python + SQL",
    question: "Compare ROW_NUMBER, RANK and DENSE_RANK.",
    answer: "ROW_NUMBER assigns a unique sequence even across ties. RANK gives tied rows the same rank and leaves gaps afterward; DENSE_RANK also ties but leaves no gaps. The right function depends on whether you need one deterministic row, competition-style placement or consecutive distinct-value groups.",
    signals: ["Tie behavior", "Gaps", "Deterministic ordering", "Use case"],
    trap: "Using RANK to select one latest record and unexpectedly returning multiple tied rows.",
    followUp: "Which function would you use to return the three highest distinct salaries per department?",
    priority: "Core",
  },
  {
    id: "sql-index",
    category: "Python + SQL",
    question: "What is a database index, and when can it hurt?",
    answer: "An index is an auxiliary data structure that helps the database locate or order rows without scanning the whole table. It can accelerate selective filters, joins and ordering, but consumes storage and adds work to inserts and updates. Column order, selectivity and the query plan determine whether an index is useful.",
    signals: ["Access path", "Selectivity", "Write cost", "Query plan"],
    trap: "Adding an index to every column or assuming the optimizer must use it.",
    followUp: "Why does column order matter in a composite B-tree index?",
    priority: "Build",
  },
  {
    id: "sql-transactions",
    category: "Python + SQL",
    question: "What transaction isolation problems should an engineer understand?",
    answer: "Concurrent transactions can observe dirty reads, non-repeatable reads, phantoms or lost updates depending on the database and isolation level. Stronger isolation reduces anomalies but can increase locking, retries or serialization failures. Choose based on the business invariant and implement safe retries where the database can abort transactions.",
    signals: ["Concurrency anomalies", "Isolation level", "Business invariant", "Retry"],
    trap: "Assuming a transaction automatically prevents every race condition.",
    followUp: "How would you prevent two workers from claiming the same job?",
    priority: "Build",
  },
  {
    id: "ml-supervised-unsupervised",
    category: "ML fundamentals",
    question: "Compare supervised and unsupervised learning.",
    answer: "Supervised learning uses labeled examples to learn a mapping from inputs to a target, such as classification or regression. Unsupervised learning searches for structure without a task label, such as clusters or lower-dimensional representations. The distinction is about the learning signal; evaluation still needs an explicit downstream objective.",
    signals: ["Labels", "Target mapping", "Structure discovery", "Evaluation objective"],
    trap: "Assuming unsupervised clusters are automatically meaningful business segments.",
    followUp: "When could self-supervised learning be useful even when labeled data is limited?",
    priority: "Core",
  },
  {
    id: "ml-train-validation-test",
    category: "ML fundamentals",
    question: "Why do we need separate train, validation and test sets?",
    answer: "The training set fits parameters; the validation set guides model, feature and threshold choices; the test set estimates performance after those choices are frozen. Repeatedly inspecting test results turns the test set into another validation set. Splits must also respect time, groups and prediction-time availability.",
    signals: ["Fit", "Selection", "Final estimate", "Split realism"],
    trap: "Tuning against the test set and still calling its result unbiased.",
    followUp: "What should you do after the test set has influenced several design decisions?",
    priority: "Core",
  },
  {
    id: "ml-overfitting",
    category: "ML fundamentals",
    question: "What is overfitting, and how would you diagnose it?",
    answer: "Overfitting occurs when a model learns training-specific noise or accidental patterns that do not generalize. A large train–validation gap, unstable cross-validation or degraded future performance can reveal it. Remedies include better splits, more representative data, regularization, simpler features/models and early stopping.",
    signals: ["Generalization gap", "Representative validation", "Regularization", "Learning curves"],
    trap: "Calling every weak validation result overfitting when both train and validation performance may indicate underfitting.",
    followUp: "How can feature leakage look like unusually successful overfitting?",
    priority: "Core",
  },
  {
    id: "ml-decision-tree",
    category: "ML fundamentals",
    question: "How does a decision tree choose a split?",
    answer: "A decision tree searches candidate feature thresholds for the split that most reduces an impurity or loss measure, such as Gini impurity or entropy for classification. It repeats recursively until stopping criteria apply. Trees capture nonlinear interactions but are high variance and can form brittle small leaves.",
    signals: ["Impurity reduction", "Recursive partition", "Nonlinearity", "High variance"],
    trap: "Assuming a locally best split guarantees the globally best tree.",
    followUp: "How do maximum depth and minimum leaf size affect bias and variance?",
    priority: "Core",
  },
  {
    id: "ml-threshold-selection",
    category: "ML fundamentals",
    question: "How do you select a classification threshold?",
    answer: "Choose the threshold on validation data using the real cost of false positives and false negatives, capacity constraints, calibration and required recall or precision. Inspect performance by important cohort and stress prevalence shifts. Freeze the policy before final evaluation and monitor it because the operating environment can change.",
    signals: ["Error cost", "Capacity", "Calibration", "Cohort checks"],
    trap: "Using 0.5 simply because the model emits probabilities.",
    followUp: "How would you choose a threshold when investigators can review only 500 alerts per day?",
    priority: "Core",
  },
  {
    id: "ml-validate-aml",
    category: "ML fundamentals",
    question: "How would you validate an AML customer risk model?",
    answer: "Use time-aware, point-in-time evaluation; measure ranking, calibration and threshold outcomes under severe imbalance; compare against policy baselines; test stability across customer and geographic cohorts; review leakage and explanation quality; and perform backtesting, UAT and governance review. Document limitations and ongoing monitoring.",
    signals: ["Time-aware split", "Imbalance", "Cohort stability", "Governance"],
    trap: "Reporting one ROC-AUC number without operational, regulatory or temporal validation.",
    followUp: "How would delayed and selectively investigated labels bias your evaluation?",
    priority: "Core",
  },
  {
    id: "llm-cosine-similarity",
    category: "LLM core",
    question: "What is cosine similarity, and what does it not tell you?",
    answer: "Cosine similarity is the normalized dot product between two vectors, measuring the angle between their directions. In embedding spaces it often approximates semantic relatedness while ignoring magnitude. It does not prove factual equivalence, entailment or usefulness for a particular query, so retrieval quality still needs labeled evaluation.",
    signals: ["Normalized dot product", "Direction", "Semantic proxy", "Not entailment"],
    trap: "Interpreting a high cosine score as confidence that a document answers the question.",
    followUp: "When might raw dot product be preferable to cosine similarity?",
    priority: "Core",
  },
  {
    id: "llm-good-prompt",
    category: "LLM core",
    question: "What makes a production prompt good?",
    answer: "A good prompt defines the task, relevant context, constraints, output contract and what to do under uncertainty. It separates trusted instructions from untrusted data and uses examples only when they clarify the boundary. Quality is established through representative evaluation, not prompt length or clever wording.",
    signals: ["Task clarity", "Constraints", "Output contract", "Evaluation"],
    trap: "Adding more instructions indefinitely instead of fixing retrieval, tools or application logic.",
    followUp: "How would you tell whether a failure belongs in the prompt or in deterministic code?",
    priority: "Core",
  },
  {
    id: "llm-system-prompt",
    category: "LLM core",
    question: "What belongs in a system prompt?",
    answer: "A system prompt should contain durable role, behavioral policy, scope, response requirements and uncertainty rules that apply across requests. Dynamic user data, retrieved documents and tool output should remain clearly delimited as untrusted content. Security-critical authorization and side-effect checks must still live in code.",
    signals: ["Durable policy", "Scope", "Data separation", "External enforcement"],
    trap: "Putting secrets or the entire application workflow into a hidden prompt and treating it as secure.",
    followUp: "Which instructions should be application code rather than prompt text?",
    priority: "Core",
  },
  {
    id: "llm-structured-output",
    category: "LLM core",
    question: "What is structured output, and when is it useful?",
    answer: "Structured output constrains a model response to a machine-readable schema such as typed JSON. It is useful when downstream code needs reliable fields for extraction, classification or workflow decisions. The application must still validate ranges, enums, cross-field invariants and whether the content is semantically justified.",
    signals: ["Schema", "Typed fields", "Downstream automation", "Semantic validation"],
    trap: "Treating schema-valid output as factually correct or safe to execute.",
    followUp: "What business invariant might be impossible to express in JSON Schema alone?",
    priority: "Core",
  },
  {
    id: "llm-function-calling",
    category: "LLM core",
    question: "What is function calling in an LLM application?",
    answer: "Function calling lets the model select from application-defined tools and propose structured arguments. The model does not execute the function; trusted application code validates identity, authorization, arguments and preconditions before execution. Results return as untrusted tool data for the next model step.",
    signals: ["Tool selection", "Proposed arguments", "Application executes", "Authorization"],
    trap: "Giving the model broad credentials or executing any schema-valid tool call automatically.",
    followUp: "Which tool actions should require explicit user confirmation?",
    priority: "Core",
  },
  {
    id: "llm-output-validation",
    category: "LLM core",
    question: "How do you validate LLM output beyond valid JSON?",
    answer: "Validate syntax and schema first, then enforce domain rules, allowed references, confidence bounds, permissions and consistency with trusted source data. Separate retryable format failures from unsafe or unsupported content. Log the validation reason and fail closed for high-impact actions.",
    signals: ["Schema", "Domain rules", "Trusted references", "Fail closed"],
    trap: "Using the same model to approve its own output without deterministic checks.",
    followUp: "How would you validate a BUY, SELL or HOLD signal before any order is placed?",
    priority: "Core",
  },
  {
    id: "rag-chunk-overlap",
    category: "RAG",
    question: "What is chunk overlap, and when does it help?",
    answer: "Chunk overlap repeats boundary text between adjacent chunks so a fact spanning a split is not lost. It can help naive fixed-size chunking, but increases index size, duplicated retrieval and context waste. Prefer structure-aware chunking first and tune overlap through retrieval and answer evaluation.",
    signals: ["Boundary preservation", "Duplication cost", "Structure first", "Empirical tuning"],
    trap: "Adding large overlap as a universal quality improvement.",
    followUp: "How can repeated overlapping chunks distort the top-k retrieval results?",
    priority: "Core",
  },
  {
    id: "rag-vector-search",
    category: "RAG",
    question: "How does vector search work in a RAG system?",
    answer: "Documents and queries are embedded into a shared vector space, then the system retrieves nearby chunk vectors using a similarity metric, often through an approximate nearest-neighbor index. Metadata filters and reranking refine candidates. Search quality depends on representation, chunking, index recall and task relevance.",
    signals: ["Shared embedding space", "Nearest neighbors", "ANN index", "Filtering/reranking"],
    trap: "Describing the vector database as if it understands truth or document permissions automatically.",
    followUp: "What is the recall–latency tradeoff in approximate nearest-neighbor search?",
    priority: "Core",
  },
  {
    id: "rag-retrieval-quality",
    category: "RAG",
    question: "How do you evaluate retrieval quality?",
    answer: "Create queries with labeled answer-bearing documents or chunks, then measure hit rate or recall@k, precision@k and ranking quality such as MRR or nDCG. Evaluate by query type, source and permission slice, and inspect misses. Retrieval evaluation should be independent from whether the generator can guess the answer.",
    signals: ["Labeled evidence", "Recall@k", "Ranking metrics", "Slices"],
    trap: "Judging retrieval only from fluent final answers.",
    followUp: "When would MRR be more informative than recall@k?",
    priority: "Core",
  },
  {
    id: "rag-answer-quality",
    category: "RAG",
    question: "How do you evaluate RAG answer quality?",
    answer: "Measure correctness, relevance, faithfulness to retrieved evidence, citation support, completeness and appropriate abstention. Combine task-specific automatic checks, calibrated judges and human review on a representative dataset. Keep retrieval diagnostics alongside answer scores so failures remain attributable.",
    signals: ["Correctness", "Faithfulness", "Citations", "Attribution"],
    trap: "Using lexical similarity to one reference answer as the sole quality metric.",
    followUp: "How would you score a correct answer that cites the wrong source?",
    priority: "Core",
  },
  {
    id: "rag-query-rewriting",
    category: "RAG",
    question: "When should a RAG system rewrite or expand a user query?",
    answer: "Query rewriting helps with conversational references, acronyms, ambiguous wording or lexical mismatch. Preserve the original intent, include relevant conversation context and generate bounded alternatives rather than replacing the query blindly. Evaluate whether rewriting improves evidence recall without introducing assumptions.",
    signals: ["Intent preservation", "Conversation resolution", "Bounded expansion", "Evaluation"],
    trap: "Letting a model invent a more convenient question than the user actually asked.",
    followUp: "How would you detect that query rewriting is reducing retrieval precision?",
    priority: "Build",
  },
  {
    id: "eval-retrieval-hit-rate",
    category: "Evaluation",
    question: "What is retrieval hit rate?",
    answer: "Retrieval hit rate is the fraction of evaluation queries for which at least one expected relevant source appears in the top-k results. It is intuitive but binary: it does not show rank, extra irrelevant chunks or whether all required evidence was found. Pair it with ranking and coverage metrics.",
    signals: ["Expected source", "Top-k", "Binary metric", "Pair with ranking"],
    trap: "Calling hit rate answer accuracy or using it without defining the expected evidence.",
    followUp: "How does hit rate change as k increases, and why is that not a free improvement?",
    priority: "Core",
  },
  {
    id: "eval-citation-accuracy",
    category: "Evaluation",
    question: "What is citation accuracy?",
    answer: "Citation accuracy measures whether each citation genuinely supports the claim attached to it and points to the correct source. Also track citation completeness: whether material claims that need evidence are cited. Evaluate at claim level, because the presence of any citation does not make the whole answer grounded.",
    signals: ["Claim-level support", "Correct source", "Completeness", "Grounding"],
    trap: "Counting citation markers without checking entailment.",
    followUp: "Who should adjudicate borderline support when documents are ambiguous?",
    priority: "Core",
  },
  {
    id: "eval-debug-bad-answer",
    category: "Evaluation",
    question: "How do you debug a bad LLM answer?",
    answer: "Reproduce the exact request with prompt, model and data versions, then inspect the pipeline in order: user input, retrieval candidates, reranking, prompt assembly, model output, tool calls and validation. Classify the failure before changing anything and add the case to a regression set after fixing it.",
    signals: ["Reproducibility", "Pipeline isolation", "Failure taxonomy", "Regression case"],
    trap: "Editing the prompt immediately without checking whether the correct evidence was retrieved.",
    followUp: "What evidence distinguishes a retrieval failure from a generation failure?",
    priority: "Core",
  },
  {
    id: "cloud-lambda-bad-fit",
    category: "Cloud + MLOps",
    question: "When is Lambda a bad fit for model inference?",
    answer: "Lambda is a poor fit when models or dependencies exceed package and memory constraints, initialization breaks latency objectives, requests run too long, specialized hardware is required or steady traffic makes dedicated serving cheaper. It can still handle authentication, validation and orchestration around a model endpoint.",
    signals: ["Artifact size", "Cold start", "Runtime/hardware", "Traffic economics"],
    trap: "Rejecting Lambda for every ML workload without considering small or infrequent models.",
    followUp: "What measurements would justify moving inference from Lambda to SageMaker?",
    priority: "Core",
  },
  {
    id: "cloud-endpoint-latency",
    category: "Cloud + MLOps",
    question: "How do you monitor and diagnose model endpoint latency?",
    answer: "Separate queueing, network, preprocessing, model inference and postprocessing latency; track percentiles rather than averages; correlate with concurrency, payload size, model version and resource saturation. Define service objectives and use traces to distinguish cold starts, throttling and model-compute regressions.",
    signals: ["Latency breakdown", "Percentiles", "Saturation", "Tracing"],
    trap: "Monitoring only average end-to-end latency.",
    followUp: "What does rising p99 with stable p50 suggest?",
    priority: "Build",
  },
  {
    id: "cloud-model-rollback",
    category: "Cloud + MLOps",
    question: "How do you design a safe model rollback?",
    answer: "Keep the previous model artifact, endpoint configuration and compatible feature contract immutable and deployable. Define rollback triggers before release, canary the new version, preserve request and prediction lineage, and test rollback regularly. If features or schemas changed, rollback may require reverting the whole compatible bundle.",
    signals: ["Immutable previous version", "Compatibility", "Triggers", "Tested procedure"],
    trap: "Assuming switching the model file is enough when upstream features also changed.",
    followUp: "How would you handle requests already in flight during rollback?",
    priority: "Core",
  },
  {
    id: "design-feature-store",
    category: "System design",
    question: "Design a feature store.",
    answer: "Define reusable feature definitions with ownership, lineage and point-in-time semantics; compute offline values for training and optionally online values for low-latency serving; keep transformations consistent; version schemas; monitor freshness and quality; and enforce access. A feature store should reduce duplication without becoming a dumping ground.",
    signals: ["Point-in-time correctness", "Offline/online consistency", "Lineage", "Freshness"],
    trap: "Focusing only on storage technology and ignoring feature definitions and ownership.",
    followUp: "How would you prevent training–serving skew?",
    priority: "Build",
  },
  {
    id: "design-model-monitoring",
    category: "System design",
    question: "Design a model monitoring system.",
    answer: "Collect service, data, prediction and outcome signals with model and feature versions. Validate schemas and freshness in real time, compute drift and cohort metrics, join delayed labels when available, and route alerts to clear runbooks. Support investigation, rollback and retraining decisions rather than dashboards alone.",
    signals: ["Four signal layers", "Versions", "Delayed labels", "Actionable alerts"],
    trap: "Alerting on every statistical drift without assessing prediction or business impact.",
    followUp: "How would you monitor a model when ground-truth labels arrive quarterly?",
    priority: "Build",
  },
  {
    id: "design-ml-ab-testing",
    category: "System design",
    question: "Design an A/B testing platform for ML models.",
    answer: "Randomize at a stable unit, log exposure before outcomes, prevent cross-group contamination, define primary and guardrail metrics, estimate sample size and run duration, and monitor experiment health. Preserve model/feature versions and support ramp-up, stopping and rollback while accounting for feedback loops.",
    signals: ["Stable randomization", "Exposure logging", "Guardrails", "Feedback effects"],
    trap: "Comparing users who happened to receive different models without randomized assignment.",
    followUp: "When would user-level randomization be unsafe or contaminated?",
    priority: "Build",
  },
  {
    id: "design-retraining-pipeline",
    category: "System design",
    question: "Design a model retraining pipeline.",
    answer: "Trigger retraining on a justified schedule or signal; create versioned point-in-time datasets; run reproducible training and evaluation; compare against the incumbent on fixed and recent slices; require approval gates; register the artifact; and deploy through canary with monitoring. Failed quality gates should leave production unchanged.",
    signals: ["Versioned data", "Incumbent comparison", "Approval gate", "Safe deployment"],
    trap: "Retraining automatically on drift without checking label quality or whether drift hurts performance.",
    followUp: "How would you avoid feedback-loop bias in newly collected training labels?",
    priority: "Build",
  },
  {
    id: "design-bank-document-qa",
    category: "System design",
    question: "Design a document Q&A system for a bank.",
    answer: "Clarify users, document classes, freshness and regulatory constraints; ingest and version content with ACLs; use authorized hybrid retrieval and reranking; assemble grounded prompts with claim-level citations; abstain when evidence is insufficient; and add audit logs, PII controls, evaluation, deletion and incident response.",
    signals: ["Bank permissions", "Grounded retrieval", "Auditability", "Abstention"],
    trap: "Designing a generic chatbot and adding security as an afterthought.",
    followUp: "How would you prove that one department cannot retrieve another department's documents?",
    priority: "Core",
  },
  {
    id: "advanced-fine-tuning",
    category: "Advanced LLM",
    question: "What is fine-tuning, and when should you avoid it?",
    answer: "Fine-tuning updates model parameters on task-specific examples to change behavior, format, style or domain performance. Avoid it when the main problem is changing factual knowledge, insufficient retrieval, weak labels or a requirement for citations. It adds data, evaluation, serving and model-governance responsibilities.",
    signals: ["Weight updates", "Behavior adaptation", "Not a knowledge database", "Operational cost"],
    trap: "Fine-tuning before establishing a prompt/RAG baseline and representative evaluation set.",
    followUp: "What evidence would convince you that prompting and RAG are no longer sufficient?",
    priority: "Advanced",
  },
  {
    id: "advanced-finetune-eval",
    category: "Advanced LLM",
    question: "How do you evaluate a fine-tuned model?",
    answer: "Compare against the base model and current production approach on a held-out, representative test set. Measure task quality, safety, calibration where relevant, robustness, general capabilities that might regress, latency and serving cost. Include human review and adversarial slices, and keep training examples out of evaluation.",
    signals: ["Base-model baseline", "Held-out set", "Regression checks", "Serving impact"],
    trap: "Reporting training loss or examples from the tuning dataset as proof of improvement.",
    followUp: "How would you detect catastrophic forgetting or style overfitting?",
    priority: "Advanced",
  },
  {
    id: "advanced-inference-optimization",
    category: "Advanced LLM",
    question: "What are the main levers for LLM inference optimization?",
    answer: "Choose an appropriately sized model; reduce prompt and output tokens; batch requests; reuse KV cache; quantize where quality permits; use optimized kernels and serving engines; and route or cache safe workloads. Evaluate end-to-end latency, throughput, memory, quality and cost on the real request distribution.",
    signals: ["Model size", "Token budget", "Batch/cache", "Quality benchmark"],
    trap: "Optimizing one kernel benchmark while user-perceived latency or answer quality gets worse.",
    followUp: "Which optimizations primarily help prefill versus autoregressive decode?",
    priority: "Advanced",
  },
  {
    id: "story-fleet-platform",
    category: "Positioning",
    question: "Explain your Fleet enterprise LLM / RAG platform project.",
    answer: "Tell the story as a platform decision: the business need, why direct team-by-team LLM calls were unsafe or inefficient, your architecture and contribution, ingestion and retrieval, gateway controls, evaluation, observability, security, adoption and the most important tradeoff. Use concrete scale or outcome evidence where available.",
    signals: ["Business need", "Your contribution", "Production controls", "Impact"],
    trap: "Listing technologies without explaining decisions, ownership or measurable value.",
    followUp: "Which platform decision would you change if usage grew tenfold?",
    priority: "Core",
  },
  {
    id: "story-crew-recommendation",
    category: "Positioning",
    question: "Explain your Crew Recommendation / SageMaker scoring architecture.",
    answer: "Start with the ranking objective and users, then explain candidate or feature inputs, why Lambda handled orchestration and SageMaker handled inference, the request/response contracts, latency target, precomputation, monitoring, fallback and your contribution. Close with impact and the next technical improvement.",
    signals: ["Ranking objective", "Service boundaries", "Contracts", "Failure handling"],
    trap: "Presenting an architecture diagram without the model objective or operational evidence.",
    followUp: "Why was ranking the right formulation instead of classification?",
    priority: "Core",
  },
];
