import type { Card } from "./study-data";

export const hkexInterviewCards: Card[] = [
  {
    id: "hkex-interview-why-hkex-cdo",
    category: "HKEX Interview",
    question: "Why HKEX, and why the Chief Data Office's Associate, Data Analytics role?",
    answerSeconds: 90,
    answer: "Connect HKEX's public role in Hong Kong's capital markets with the kind of work you have evidence for: turning complex financial data into reliable, governed products and coordinating delivery across technical and business teams. The role is attractive because its Enterprise Data Platform is not an isolated reporting tool; public HKEX material describes governed sharing, a Data Marketplace and firmwide analytics, so data quality, access and lineage have real institutional impact. Name two immediate contributions—such as SQL/Python data delivery and risk-aware stakeholder coordination—and one area you want to deepen, such as enterprise metadata or cloud implementation. Close on fit, not prestige.",
    signals: ["HKEX public-market purpose", "EDP and governed data", "Two evidence-backed contributions", "Specific growth edge"],
    trap: "Giving a generic financial-services answer, praising HKEX's brand, or implying that the coordination elements are less valuable than hands-on coding.",
    followUp: "Which one of your past projects most directly proves you can advance HKEX's data strategy without overstating your ownership?",
    priority: "Core",
  },
  {
    id: "hkex-interview-positioning-delivery-role",
    category: "HKEX Interview",
    question: "This role spans analytics, technical delivery and project coordination. Where are you strongest, and where would you need support?",
    answerSeconds: 120,
    answer: "Choose a coherent center of gravity rather than claiming equal mastery everywhere. A strong positioning is technical delivery: you can inspect data, reason about architecture and controls, and translate between engineers, analysts, risk and business stakeholders. Prove it with one project where you owned concrete artifacts and delivery decisions. Then name a real but bounded gap—perhaps a specific HKEX cloud or metadata tool—and give a learning plan based on adjacent experience, documentation, a sandbox and early expert review. Make clear that you know when to lead, when to coordinate and when a specialist owns the decision.",
    signals: ["Coherent strength", "Concrete ownership evidence", "Honest bounded gap", "Clear decision boundaries"],
    trap: "Presenting project coordination as administration, or answering with an unbounded weakness that is central to the role.",
    followUp: "Which HKEX delivery decision would you deliberately escalate to an architect, security specialist or data owner rather than make alone?",
    priority: "Core",
  },
  {
    id: "hkex-interview-governed-edp-ingestion",
    category: "HKEX Interview",
    question: "Walk through onboarding a new market-data source onto HKEX's Enterprise Data Platform from initiation to production.",
    answerSeconds: 180,
    answer: "Start with the business outcome, consumers, criticality, data owner and measurable acceptance criteria. Profile the source and agree a contract covering keys, schema, timing, corrections, retention and permitted use. Design raw immutable landing, validated and quarantined paths, curated models, metadata, lineage and least-privilege access. Make ingestion replayable with stable source identity; add schema, freshness, completeness, uniqueness and reconciliation controls with thresholds owned by the business. Plan environments, testing, security review, operational runbooks, backfill, cutover and rollback through the SDLC. Release incrementally, compare control totals, monitor both pipeline and data SLOs, and transfer ownership with documentation and evidence rather than declaring success when the first load completes.",
    signals: ["Source contract and owner", "Layered replayable ingestion", "Quality and lineage controls", "Operational acceptance"],
    trap: "Starting with a tool diagram and omitting source semantics, business reconciliation, access approval or post-release ownership.",
    followUp: "What would stop you from publishing this HKEX dataset even if the pipeline completed successfully and on schedule?",
    priority: "Core",
  },
  {
    id: "hkex-interview-access-control-design",
    category: "HKEX Interview",
    question: "Design access control for analysts, engineers and vendors across raw, curated and reporting data using LDAP, OAuth or Keycloak concepts.",
    answerSeconds: 180,
    answer: "Separate identity, authentication, authorization and data enforcement. Federate workforce identity from the authoritative directory; use OAuth/OIDC through an identity provider such as Keycloak for short-lived sessions and service identities, then map governed groups or roles to approved platform entitlements. Enforce access at the storage, catalog, query and visualization layers—UI hiding is not authorization. Raw sensitive data receives the narrowest access; curated and reporting layers apply masking, row or column restrictions and purpose-based roles. Use an owner-approved request with expiry and segregation of duties, log grants and data access, review entitlements periodically, and revoke promptly when role or vendor status changes. Test negative access paths and emergency removal, not only successful login.",
    signals: ["Identity versus authorization", "Layered enforcement", "Time-bounded approval", "Audit and recertification"],
    trap: "Treating LDAP groups, an OAuth token or a Keycloak role as sufficient by itself without enforcement on the actual data systems.",
    followUp: "How would HKEX prevent a vendor's valid login from becoming broad access to unrelated datasets in the same platform?",
    priority: "Build",
  },
  {
    id: "hkex-interview-lineage-quality-rollout",
    category: "HKEX Interview",
    question: "HKEX wants enterprise lineage and data-quality coverage, but teams use different tools and definitions. How would you roll it out incrementally?",
    answerSeconds: 180,
    answer: "Begin with critical data elements and high-impact reports rather than promising complete lineage for everything. Define ownership, minimum metadata, common identifiers and evidence standards; map source-to-report lineage for one domain and validate it with engineers and business owners. Automate technical lineage from orchestration, SQL and catalog integrations where reliable, then add manually governed business lineage for meanings the tools cannot infer. Pair lineage with a small quality rule set—freshness, completeness, uniqueness, validity and reconciled amounts—with owner-approved thresholds and incident routing. Measure coverage, stale metadata, rule reliability and time to impact analysis. Publish limitations, repair false lineage, and expand only after the pilot produces useful incident and change-management outcomes.",
    signals: ["Critical-data pilot", "Technical plus business lineage", "Owner-approved quality rules", "Measured incremental adoption"],
    trap: "Buying a metadata tool and equating harvested tables and columns with trusted end-to-end lineage or agreed business meaning.",
    followUp: "Which HKEX metric would show that lineage is improving risk decisions rather than only increasing catalog coverage?",
    priority: "Build",
  },
  {
    id: "hkex-interview-jupyterhub-governance",
    category: "HKEX Interview",
    question: "How would you operate JupyterHub as a useful but controlled enterprise data-science workbench?",
    answerSeconds: 150,
    answer: "Authenticate through enterprise SSO and authorize data separately with user or service identities, least-privilege roles and short-lived credentials. Isolate users and workloads, set CPU, memory and idle limits, restrict network destinations, and keep secrets out of notebooks. Provide approved, versioned base images and package channels so analysis is reproducible; scan dependencies and separate exploratory from production environments. Mount or query governed datasets rather than copying uncontrolled extracts, apply masking and export controls, log access and image versions, and define retention and cleanup. Promotion to production should move reviewed code and tests into a pipeline—not schedule a personal notebook as an undocumented critical job.",
    signals: ["SSO plus data authorization", "Isolated resource controls", "Reproducible approved images", "Reviewed production promotion"],
    trap: "Securing the JupyterHub login while notebooks can still retrieve broad credentials, install arbitrary packages or export sensitive results.",
    followUp: "What would HKEX preserve so an analysis from six months ago can be reproduced after the notebook image and source tables have changed?",
    priority: "Build",
  },
  {
    id: "hkex-interview-capital-markets-model",
    category: "HKEX Interview",
    question: "Sketch a warehouse model for securities, issuers, market participants and executed trades. State the grain before naming tables.",
    answerSeconds: 180,
    answer: "Set the core fact grain to one authoritative executed trade event or one explicitly defined allocation if a trade can split; never mix both grains. Keep stable source identifiers, event and processing times, market, security, participant roles, quantity, exact price, currency, status and correction lineage. Model securities, issuers, venues, currencies and participants as governed dimensions, using effective-dated history only where analytical questions require the as-of attribute. Derive daily aggregates from the atomic fact and reconcile count, quantity and turnover to trusted source controls. Clarify cancellations, corrections, late events, cross-market identifiers, corporate actions and business calendars. Document which fields are sensitive and ensure row multiplication cannot arise from overlapping dimension versions.",
    signals: ["Explicit atomic grain", "Effective-dated dimensions", "Correction semantics", "Control-total reconciliation"],
    trap: "Starting with a generic star-schema diagram without deciding whether a row is a trade, execution, allocation, order or daily aggregate.",
    followUp: "Which HKEX questions require an as-of security or issuer dimension rather than today's current attributes?",
    priority: "Core",
  },
  {
    id: "hkex-interview-cloud-open-source-decision",
    category: "HKEX Interview",
    question: "How would you evaluate a cloud or open-source capability for HKEX's data platform without turning the decision into a feature checklist?",
    answerSeconds: 150,
    answer: "Start with workload and control requirements: data classification and residency, latency, scale, availability, recovery, integration, identity, lineage, portability, support and total operating cost. Define weighted acceptance tests and a representative proof of concept using sanitized or synthetic data. Evaluate the shared-responsibility boundary, encryption and key control, audit evidence, patching, vulnerability response, vendor concentration, exit path and skills needed to operate it. Compare managed service, self-hosted open source and existing-platform options, including the cost of people and failure—not only license price. Record the decision, assumptions and residual risks, obtain architecture and security approval, and stage adoption with rollback and measurable outcomes.",
    signals: ["Workload-led criteria", "Control and residency assessment", "Operational total cost", "Reversible evidence-based choice"],
    trap: "Selecting a product because it is cloud-native or open source without assigning operational ownership and testing HKEX control requirements.",
    followUp: "What finding in an HKEX proof of concept would cause you to reject the technically fastest option?",
    priority: "Build",
  },
  {
    id: "hkex-interview-vendor-security-block",
    category: "HKEX Interview",
    question: "A vendor's lineage connector is two weeks from release, but security finds that it requires broad production credentials. What do you do?",
    answerSeconds: 150,
    answer: "Do not trade an unresolved access risk for the date. Reproduce and document the exact required permissions, affected data and vendor data flow, then bring security, architecture, platform owner, data owner and vendor together around the control objective. Test whether scoped read-only credentials, a proxy, metadata export, private connectivity or phased dataset coverage can meet the requirement. Re-estimate schedule, cost and residual risk transparently; record who can accept which risk and do not accept it on their behalf. If no compliant design exists, block production, preserve completed work and offer a limited non-production or lower-sensitivity pilot. Update the dependency and vendor-risk record and capture the requirement earlier in future procurement.",
    signals: ["Evidence before escalation", "Least-privilege alternatives", "Named risk owner", "Safe phased option"],
    trap: "Letting the vendor's deadline redefine HKEX's security boundary, or saying no without exploring a controlled technical alternative.",
    followUp: "How would you explain the delay to an HKEX sponsor who sees the connector as a low-risk metadata tool?",
    priority: "Core",
  },
  {
    id: "hkex-interview-prioritize-value-risk",
    category: "HKEX Interview",
    question: "Two business teams want the same EDP delivery slot: one has high visible value; the other closes a serious data-control gap. How do you prioritize?",
    answerSeconds: 150,
    answer: "Make the criteria explicit before debating teams: regulatory or control severity, customer and market impact, time criticality, expected business value, dependencies, effort, reversibility and confidence in the evidence. A serious unmanaged control gap can be mandatory rather than simply another weighted feature. Confirm the risk rating and deadline with the accountable risk or data owner, split work if a small containment removes immediate exposure, and identify whether either request has an alternative. Present options and consequences to the decision owner, record the rationale, communicate it to both teams, and revisit when evidence changes. Do not disguise a governance decision as a private engineering preference.",
    signals: ["Explicit decision criteria", "Mandatory control threshold", "Containment option", "Recorded accountable decision"],
    trap: "Prioritizing the loudest sponsor or using an opaque score that treats severe data risk as interchangeable with ordinary feature value.",
    followUp: "What evidence would let HKEX safely defer the control-gap work for one release?",
    priority: "Core",
  },
  {
    id: "hkex-interview-hybrid-agile-sdlc",
    category: "HKEX Interview",
    question: "What does a hybrid Agile approach look like inside a controlled HKEX SDLC?",
    answerSeconds: 150,
    answer: "Use iterative discovery and delivery within explicit lifecycle controls. Maintain a prioritized backlog with user value, data and non-functional acceptance criteria; deliver thin vertical slices and demonstrate them frequently to users and control partners. In parallel, retain traceable requirements, architecture decisions, threat and data-risk assessment, segregation of duties, code review, automated tests, environment promotion, change approval, rollback and operational readiness. Place security, data governance and support representatives into refinement rather than handing work to them at the end. Define what evidence each release must produce and automate it where possible. Agile changes feedback cadence and batch size; it does not remove accountability or allow documentation to be reconstructed after production.",
    signals: ["Iterative vertical slices", "Traceable release evidence", "Controls shifted left", "Rollback and readiness"],
    trap: "Calling governance a waterfall phase after development, or using Agile language to justify changing scope without updating risk, evidence and commitments.",
    followUp: "Which HKEX release controls would remain mandatory even for a one-line data-transformation change?",
    priority: "Core",
  },
  {
    id: "hkex-interview-metric-definition-conflict",
    category: "HKEX Interview",
    question: "Two senior stakeholders use different definitions of daily turnover and each wants theirs in the enterprise dashboard. How do you resolve it?",
    answerSeconds: 150,
    answer: "Do not force consensus by choosing one SQL expression privately. Write both definitions in testable terms: grain, included statuses, corrections, currencies, time boundary, source and intended decision. Quantify where and why results diverge on representative days, then bring the metric owner, consumers, finance or risk and data engineering to decide whether there is one canonical metric or two legitimately named metrics for different purposes. Record the decision in the semantic layer with owner, formula, dimensions, exclusions, lineage, effective date and examples. Version downstream changes, communicate impact and reconcile the first releases. Escalate the ownership decision if needed while keeping the technical evidence neutral.",
    signals: ["Executable definitions", "Quantified divergence", "Named metric owner", "Versioned semantic contract"],
    trap: "Averaging the results, picking the more senior stakeholder's formula, or publishing two identically named measures that users cannot distinguish.",
    followUp: "How would HKEX prevent a notebook author from recreating the deprecated definition after the canonical metric is approved?",
    priority: "Core",
  },
];
