import type { Card } from "./study-data";

export const rapidFireCards: Card[] = [
  {
    id: "rapid-ai-generative-discriminative",
    category: "AI rapid fire",
    question: "What is the difference between a generative and a discriminative model?",
    answer: "A discriminative model learns a decision boundary or conditional target distribution, such as P(y|x). A generative model learns how data is produced, such as a joint distribution or next-token distribution, and can generate new samples. The distinction is about the modeled objective, not whether the system happens to output text.",
    signals: ["Conditional vs data distribution", "Decision boundary", "Generation", "Objective matters"],
    trap: "Calling every neural network generative or assuming generative models are always better classifiers.",
    followUp: "Where would a generative model add value beyond a discriminative classifier?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ai-pretraining-finetuning-inference",
    category: "AI rapid fire",
    question: "Compare pretraining, fine-tuning and inference.",
    answer: "Pretraining learns broad model parameters from a large general corpus. Fine-tuning updates some or all parameters on narrower data to adapt behavior or capability. Inference keeps parameters fixed and runs the model to produce outputs, although prompts, retrieved context and decoding settings still affect each result.",
    signals: ["Broad learning", "Task adaptation", "Fixed weights at inference", "Runtime context"],
    trap: "Saying prompting changes model weights or treating fine-tuning as a way to inject frequently changing facts.",
    followUp: "Which problem would you solve with retrieval rather than fine-tuning?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ai-tokenization",
    category: "AI rapid fire",
    question: "What is tokenization, and why does it matter?",
    answer: "Tokenization converts text into vocabulary IDs the model can process, often using subword units rather than whole words. It affects context usage, cost, latency and how well unusual languages, code or domain terms are represented. Token count is model-specific and is not the same as word count.",
    signals: ["Vocabulary IDs", "Subword units", "Context and cost", "Model-specific"],
    trap: "Assuming one token equals one word or that every model tokenizes the same input identically.",
    followUp: "Why can tokenization make some languages more expensive to serve than others?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ai-temperature-top-p",
    category: "AI rapid fire",
    question: "What is the difference between temperature and top-p sampling?",
    answer: "Temperature rescales the logits before sampling: lower values sharpen the distribution and higher values flatten it. Top-p limits sampling to the smallest token set whose cumulative probability reaches p. Both control decoding variability, not model knowledge, and deterministic business flows usually need stronger constraints than sampling settings alone.",
    signals: ["Logit scaling", "Probability mass cutoff", "Variability", "Not factuality controls"],
    trap: "Claiming temperature zero guarantees factual or perfectly repeatable output across all serving environments.",
    followUp: "How would you configure decoding for schema-constrained extraction versus creative drafting?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ai-context-window",
    category: "AI rapid fire",
    question: "What is an LLM context window?",
    answer: "The context window is the maximum token budget available to the model for the prompt, retrieved content, conversation history and generated output. More context does not guarantee better use of every detail and increases cost and often latency. Applications must budget tokens and select relevant context rather than blindly filling the window.",
    signals: ["Total token budget", "Input plus output", "Cost and latency", "Context selection"],
    trap: "Treating the context window as durable memory or assuming information anywhere inside it will be used reliably.",
    followUp: "What would you remove first when a RAG prompt exceeds its context budget?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ai-encoder-decoder",
    category: "AI rapid fire",
    question: "Encoder-only vs decoder-only vs encoder-decoder models: when does each fit?",
    answer: "Encoder-only models build contextual representations and fit tasks such as classification or embeddings. Decoder-only models predict tokens autoregressively and dominate general text generation. Encoder-decoder models encode an input then generate an output, which naturally fits sequence-to-sequence tasks such as translation or summarization.",
    signals: ["Representation", "Autoregressive generation", "Sequence-to-sequence", "Workload fit"],
    trap: "Presenting the architectures as strict capability boundaries rather than strong design tendencies.",
    followUp: "Why might an encoder model be more efficient than a generative LLM for classification?",
    priority: "Build",
    answerSeconds: 45,
  },
  {
    id: "rapid-ai-autoregressive-decoding",
    category: "AI rapid fire",
    question: "What does autoregressive decoding mean?",
    answer: "An autoregressive model generates one token at a time, conditioning each new token on the prompt and all previously generated tokens. This makes generation sequential, so output length directly affects latency and errors can compound. The KV cache avoids recomputing attention state for the entire prefix at every step.",
    signals: ["One token at a time", "Condition on prefix", "Sequential latency", "KV cache"],
    trap: "Assuming all output tokens can be generated independently in one parallel operation.",
    followUp: "Why does a long generated answer usually cost more latency than a prompt of the same length?",
    priority: "Build",
    answerSeconds: 45,
  },
  {
    id: "rapid-ai-attention-mask",
    category: "AI rapid fire",
    question: "What does an attention mask do?",
    answer: "An attention mask prevents selected token positions from contributing to attention. A causal mask blocks a decoder from seeing future tokens during next-token prediction, while a padding mask hides placeholder positions in batched sequences. Masks enforce visibility rules; they do not remove the underlying token data from the request.",
    signals: ["Visibility control", "Causal mask", "Padding mask", "Not data deletion"],
    trap: "Confusing an attention mask with a security boundary or with the learned attention weights themselves.",
    followUp: "What would break during training if a causal language model could attend to future tokens?",
    priority: "Build",
    answerSeconds: 45,
  },
  {
    id: "rapid-ai-prompt-injection-jailbreak",
    category: "AI rapid fire",
    question: "Prompt injection vs jailbreak: what is the distinction?",
    answer: "Prompt injection is untrusted input attempting to override instructions or manipulate tool and data access; it may be direct from a user or indirect from retrieved content. A jailbreak is a prompt designed to bypass the model's safety behavior. They overlap, but injection is primarily an application trust-boundary problem and must be contained with authorization and tool controls.",
    signals: ["Untrusted instructions", "Direct or indirect", "Safety bypass", "Application controls"],
    trap: "Trying to solve prompt injection only by adding a stronger system prompt.",
    followUp: "How would you keep a malicious retrieved document from triggering a privileged tool?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ai-ttft-tpot",
    category: "AI rapid fire",
    question: "What are time to first token and time per output token?",
    answer: "Time to first token measures the delay before generation begins and is influenced by queueing and prompt prefill. Time per output token measures the cadence of subsequent decoding tokens. Track both with end-to-end latency because a fast first token can still hide slow completion for long responses.",
    signals: ["Queue plus prefill", "Decode cadence", "Streaming experience", "End-to-end latency"],
    trap: "Reporting only average total latency and missing poor startup or decoding behavior at the tail.",
    followUp: "Which optimization would help a long prompt with a short answer versus a short prompt with a long answer?",
    priority: "Build",
    answerSeconds: 45,
  },

  {
    id: "rapid-ml-data-concept-drift",
    category: "ML rapid fire",
    question: "What is data drift, and how is it different from concept drift?",
    answer: "Data drift means the production input distribution has changed from the reference distribution. Concept drift means the relationship between inputs and the target has changed, so P(y|x) differs. Input drift is observable without labels, but it is only a warning signal; outcome data is usually needed to prove model degradation or concept drift.",
    signals: ["Input distribution", "Target relationship", "Labels", "Warning vs failure"],
    trap: "Automatically retraining whenever a feature distribution moves, even when model performance is stable.",
    followUp: "How would you investigate drift when ground-truth labels arrive six weeks late?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ml-batch-online-learning",
    category: "ML rapid fire",
    question: "Batch learning vs online learning: what is the tradeoff?",
    answer: "Batch learning periodically trains on a bounded dataset, making runs easier to reproduce, validate and roll back. Online learning updates the model incrementally as observations arrive, adapting faster but increasing sensitivity to ordering, bad data and feedback loops. Choose based on how quickly the target changes and whether safe continuous evaluation is possible.",
    signals: ["Periodic retraining", "Incremental updates", "Adaptation speed", "Operational risk"],
    trap: "Calling real-time prediction online learning even when the model weights never update online.",
    followUp: "What guardrails would you require before allowing production events to update a model automatically?",
    priority: "Build",
    answerSeconds: 45,
  },
  {
    id: "rapid-ml-parametric-nonparametric",
    category: "ML rapid fire",
    question: "Parametric vs non-parametric models: what does that mean?",
    answer: "A parametric model has a fixed-form parameterization whose size does not grow directly with the training set, such as linear regression. A non-parametric model can increase effective complexity with more data, such as k-nearest neighbors. Non-parametric does not mean no parameters, and both families still make assumptions.",
    signals: ["Fixed form", "Complexity can grow", "Examples", "Both make assumptions"],
    trap: "Saying non-parametric models have no parameters or are automatically more flexible in every implementation.",
    followUp: "How do their memory and inference costs tend to differ as the dataset grows?",
    priority: "Build",
    answerSeconds: 45,
  },
  {
    id: "rapid-ml-bagging-boosting",
    category: "ML rapid fire",
    question: "Bagging vs boosting: what is the difference?",
    answer: "Bagging trains models largely independently on resampled data and aggregates them, mainly reducing variance; Random Forest is the classic example. Boosting trains weak learners sequentially so each stage focuses on residual errors, often reducing bias but becoming more sensitive to noise and tuning. Parallelism and failure behavior differ as well.",
    signals: ["Independent ensembles", "Variance reduction", "Sequential residual fitting", "Noise sensitivity"],
    trap: "Saying both methods simply average many trees and therefore behave the same.",
    followUp: "Why is a Random Forest easier to parallelize than gradient boosting?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ml-calibration-discrimination",
    category: "ML rapid fire",
    question: "What is the difference between discrimination and calibration?",
    answer: "Discrimination measures whether a model ranks positive cases above negative ones, often summarized by ROC-AUC or PR-AUC. Calibration measures whether predicted probabilities match observed frequencies, such as whether cases scored 0.8 are positive about 80% of the time. A model can rank well while producing unreliable probabilities.",
    signals: ["Ranking", "Probability reliability", "Independent properties", "Decision impact"],
    trap: "Assuming a high AUC proves that probability thresholds have a reliable business interpretation.",
    followUp: "When would you recalibrate a model instead of retraining its ranking function?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ml-feature-scaling",
    category: "ML rapid fire",
    question: "Why does feature scaling matter for some models but not others?",
    answer: "Distance-based and gradient-based models can be dominated by features with larger numeric scales, so standardization often improves geometry and optimization. Tree splits depend mainly on ordering and are generally insensitive to monotonic rescaling. Fit every scaling transformation on training data only to avoid leakage.",
    signals: ["Distance geometry", "Optimization", "Trees", "Train-only fit"],
    trap: "Standardizing the full dataset before splitting or scaling blindly without considering the algorithm.",
    followUp: "Would you standardize one-hot features and skewed continuous features in the same way?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ml-cross-validation",
    category: "ML rapid fire",
    question: "What does cross-validation estimate, and when can it mislead you?",
    answer: "Cross-validation repeats training and validation across folds to estimate how model selection may generalize and to show variability. It misleads when folds violate deployment reality—for example by mixing future with past, the same user across folds or dependent observations. The splitting strategy matters more than the number of folds.",
    signals: ["Repeated folds", "Generalization estimate", "Variance", "Realistic split"],
    trap: "Using random k-fold validation for temporal data and reporting a precise but leaked estimate.",
    followUp: "Which split would you use for customer-level churn data collected over time?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ml-gradient-descent",
    category: "ML rapid fire",
    question: "Batch, stochastic and mini-batch gradient descent: how do they differ?",
    answer: "Batch gradient descent computes each update from the full dataset, giving stable but expensive steps. Stochastic gradient descent updates from one example, producing noisy but frequent steps. Mini-batch training balances efficient vectorized hardware use with useful gradient noise and is the normal choice for modern neural networks.",
    signals: ["Full dataset", "Single example", "Mini-batch compromise", "Hardware efficiency"],
    trap: "Confusing an epoch with one optimization step or assuming larger batches always converge better.",
    followUp: "Why might learning rate need to change when batch size changes substantially?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ml-class-weights-resampling",
    category: "ML rapid fire",
    question: "Class weights vs resampling: how do you handle imbalance?",
    answer: "Class weights increase the loss contribution of selected classes without changing the dataset. Resampling changes class representation by over- or under-sampling, which can improve learning but may duplicate noise or discard useful examples. Compare both using realistic validation prevalence and select the operating threshold separately.",
    signals: ["Loss weighting", "Data distribution", "Noise or information loss", "Realistic validation"],
    trap: "Balancing the test set or assuming either method removes the need for threshold selection.",
    followUp: "When could oversampling before the train-validation split leak information?",
    priority: "Build",
    answerSeconds: 45,
  },
  {
    id: "rapid-ml-pca",
    category: "ML rapid fire",
    question: "What does PCA do?",
    answer: "Principal component analysis finds orthogonal directions that capture descending variance and projects data into that basis. It can compress correlated numeric features and aid visualization, but high variance is not necessarily predictive signal. Scaling and fitting only on training data are important, and the transformed features may be hard to interpret.",
    signals: ["Orthogonal components", "Variance", "Dimensionality reduction", "Interpretability tradeoff"],
    trap: "Describing PCA as feature selection or assuming its first components are best for the target.",
    followUp: "How would you choose the number of components without looking at the test labels?",
    priority: "Build",
    answerSeconds: 45,
  },

  {
    id: "rapid-de-sync-async",
    category: "Data engineering rapid fire",
    question: "What is the difference between a synchronous and an asynchronous function?",
    answer: "A synchronous function occupies its execution path until its work returns. An asynchronous function can suspend while waiting for I/O so the event loop can run other tasks, but CPU work still blocks unless moved or parallelized separately. Async improves concurrency for wait-heavy workloads; it does not make each operation intrinsically faster.",
    signals: ["Blocking execution", "Suspend on I/O", "Event loop", "Concurrency not speed"],
    trap: "Marking a function async while calling blocking libraries inside it, which still stalls the event loop.",
    followUp: "When would threads or processes be a better fit than async I/O?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-de-oltp-olap",
    category: "Data engineering rapid fire",
    question: "OLTP vs OLAP: what is the difference?",
    answer: "OLTP systems serve many small, concurrent transactions with low latency and strong operational consistency. OLAP systems scan and aggregate large histories for analytics, favoring columnar storage and distributed compute. Separate them when analytical scans would compete with production writes or when their data models and freshness needs differ.",
    signals: ["Transactions", "Analytical scans", "Concurrency", "Workload isolation"],
    trap: "Treating OLTP and OLAP as product names rather than workload patterns with different designs.",
    followUp: "When is a read replica insufficient for isolating an analytical workload?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-de-partition-shard",
    category: "Data engineering rapid fire",
    question: "Partitioning vs sharding: how do they differ?",
    answer: "Partitioning divides a dataset into pieces according to a key or range and can occur inside one system. Sharding usually means distributing those partitions across independent database or compute nodes. Both improve pruning or scale, but shard routing, rebalancing and cross-shard operations add distributed-systems complexity.",
    signals: ["Data division", "Across nodes", "Routing", "Rebalancing"],
    trap: "Using the terms interchangeably without stating whether data crosses independent failure and ownership boundaries.",
    followUp: "What makes a tenant ID a good or bad shard key?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-de-normalization-denormalization",
    category: "Data engineering rapid fire",
    question: "Normalization vs denormalization: what is the tradeoff?",
    answer: "Normalization separates facts to reduce redundancy and update anomalies, which suits transactional integrity. Denormalization duplicates or prejoins data to simplify and accelerate read-heavy queries. The tradeoff is write complexity and consistency versus query simplicity and performance; the right choice follows the workload and ownership model.",
    signals: ["Redundancy", "Update anomalies", "Read performance", "Workload-driven"],
    trap: "Assuming normalized is always correct or denormalized data needs no consistency strategy.",
    followUp: "How would you keep a denormalized customer attribute correct after source updates?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-de-queue-pubsub",
    category: "Data engineering rapid fire",
    question: "Queue vs publish-subscribe: when would you use each?",
    answer: "A work queue normally distributes each task to one competing consumer for processing. Publish-subscribe delivers each event to multiple independent subscriptions so different consumers can react. Real brokers mix these patterns, so define retention, acknowledgement, ordering and replay semantics rather than relying only on the label.",
    signals: ["Competing consumers", "Fan-out", "Acknowledgement", "Replay semantics"],
    trap: "Assuming every subscriber automatically receives every message exactly once.",
    followUp: "Which pattern fits image-processing jobs versus broadcasting an order-created event?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-de-backpressure",
    category: "Data engineering rapid fire",
    question: "What is backpressure?",
    answer: "Backpressure is the mechanism by which a slower downstream stage limits upstream production so buffers do not grow without bound. Systems implement it with bounded queues, demand signals, rate limits, flow control or load shedding. It converts overload from uncontrolled memory growth into an explicit latency, rejection or degradation policy.",
    signals: ["Downstream capacity", "Bounded buffers", "Flow control", "Overload policy"],
    trap: "Adding a larger queue and calling the overload problem solved while latency and memory continue to grow.",
    followUp: "What would you monitor to distinguish a brief burst from sustained downstream saturation?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-de-offset-checkpoint",
    category: "Data engineering rapid fire",
    question: "What is the difference between an offset and a checkpoint?",
    answer: "An offset identifies a position in an ordered input log, such as the next Kafka record to consume. A checkpoint is a durable snapshot of processing progress and may include offsets plus operator state, timers and metadata needed for recovery. Committing an offset alone does not preserve a stateful computation consistently.",
    signals: ["Log position", "Durable recovery state", "Stateful operators", "Consistent boundary"],
    trap: "Assuming a committed input offset proves the corresponding sink output was published exactly once.",
    followUp: "When should a pipeline make its output visible relative to checkpoint completion?",
    priority: "Build",
    answerSeconds: 45,
  },
  {
    id: "rapid-de-lake-warehouse",
    category: "Data engineering rapid fire",
    question: "Data lake vs data warehouse: what is the distinction?",
    answer: "A data lake stores large volumes of varied data in open or low-cost object storage, often preserving raw inputs for replay. A warehouse provides managed tables, governance and query performance for curated analytics. Modern platforms overlap, so evaluate transaction support, catalog, workload isolation, cost and operational maturity instead of treating the names as strict boundaries.",
    signals: ["Raw varied data", "Curated analytics", "Storage and governance", "Converging platforms"],
    trap: "Equating a data lake with an ungoverned collection of files or assuming warehouses cannot store semi-structured data.",
    followUp: "Which data would you retain only in the raw lake layer, and for how long?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-de-natural-surrogate-key",
    category: "Data engineering rapid fire",
    question: "Natural key vs surrogate key: when would you use each?",
    answer: "A natural key comes from the business domain, such as a stable account identifier. A surrogate key is a generated identifier used internally, insulating joins from changing or composite business keys and supporting historical dimension versions. Surrogate keys do not remove the need to enforce the real business uniqueness rule.",
    signals: ["Business identity", "Generated identity", "Change isolation", "Uniqueness constraint"],
    trap: "Adding a surrogate ID while allowing duplicate rows for the same natural business entity.",
    followUp: "Why is a surrogate key useful in a Type 2 slowly changing dimension?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-de-lineage",
    category: "Data engineering rapid fire",
    question: "What is data lineage?",
    answer: "Data lineage records how data moves from sources through transformations into downstream tables, metrics and products. It supports impact analysis, incident diagnosis, governance and safe schema changes. Useful lineage includes ownership and field-level semantics where needed; a graph with no freshness or operational integration is only documentation.",
    signals: ["Sources to consumers", "Transformations", "Impact analysis", "Ownership"],
    trap: "Treating lineage as automatically correct because a tool generated a dependency graph.",
    followUp: "How would lineage help during a breaking source-column change?",
    priority: "Core",
    answerSeconds: 45,
  },

  {
    id: "rapid-ds-population-sample",
    category: "Data science rapid fire",
    question: "What is the difference between a population and a sample?",
    answer: "The population is the full group about which you want to make a claim; a sample is the observed subset used to estimate population properties. Valid inference depends on how that sample was selected, not only its size. A large biased sample can be less useful than a smaller representative one.",
    signals: ["Target group", "Observed subset", "Selection mechanism", "Representativeness"],
    trap: "Assuming more rows automatically eliminate selection bias.",
    followUp: "How would non-response change the population your survey results actually represent?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ds-correlation-causation",
    category: "Data science rapid fire",
    question: "Why does correlation not imply causation?",
    answer: "Correlation shows variables move together, but the relationship may be caused by a confounder, reverse causality, selection bias or chance. A causal claim needs an identification strategy, ideally randomization or a defensible quasi-experimental design. Domain knowledge and a causal graph help state which assumptions are required.",
    signals: ["Association", "Confounding", "Reverse causality", "Identification strategy"],
    trap: "Adding more control variables without checking whether they are confounders, mediators or colliders.",
    followUp: "Give a plausible confounder in the relationship between product usage and customer retention.",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ds-confidence-interval",
    category: "Data science rapid fire",
    question: "What does a 95% confidence interval mean?",
    answer: "Under the model and repeated-sampling procedure, 95% of intervals constructed this way would contain the true parameter. For one computed frequentist interval, the parameter is fixed; it is not literally a 95% probability statement about that parameter. The interval also reflects sampling uncertainty, not every source of bias or model error.",
    signals: ["Repeated sampling", "Procedure coverage", "Fixed parameter", "Sampling uncertainty"],
    trap: "Saying there is a 95% probability that the true value lies inside this already-computed frequentist interval.",
    followUp: "Why can a narrow confidence interval still support a badly biased estimate?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ds-p-value",
    category: "Data science rapid fire",
    question: "What does a p-value tell you?",
    answer: "A p-value is the probability, assuming the null model and its assumptions, of observing a test statistic at least as extreme as the one obtained. It is not the probability that the null hypothesis is true and does not measure effect size or business importance. Interpret it with the design, assumptions, interval and practical impact.",
    signals: ["Conditional on null", "Extreme statistic", "Not null probability", "Effect size separate"],
    trap: "Turning p < 0.05 into proof that an effect is real, large or useful.",
    followUp: "How does testing many metrics change the meaning of isolated small p-values?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ds-type-errors",
    category: "Data science rapid fire",
    question: "What are Type I and Type II errors?",
    answer: "A Type I error rejects a true null hypothesis—a false positive—and its probability is controlled by alpha under the test assumptions. A Type II error fails to reject a false null—a false negative—and one minus its probability is statistical power. The acceptable balance depends on the real cost of each decision error.",
    signals: ["False positive", "False negative", "Alpha", "Power and costs"],
    trap: "Describing failure to reject the null as proof that the null is true.",
    followUp: "Which error would concern you more when testing a safety-critical model change?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ds-statistical-power",
    category: "Data science rapid fire",
    question: "What is statistical power?",
    answer: "Power is the probability that a test detects a specified true effect under its assumptions. It increases with sample size, larger effect size, lower variance and, with a tradeoff, a higher significance threshold. Power analysis should use the minimum effect worth acting on, not an unrealistically optimistic effect.",
    signals: ["Detect true effect", "Sample size", "Variance", "Minimum detectable effect"],
    trap: "Doing power analysis after looking at results and treating low power as an explanation that proves the desired effect exists.",
    followUp: "How would a noisy primary metric affect the sample size needed for an experiment?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ds-confounder",
    category: "Data science rapid fire",
    question: "What is a confounder?",
    answer: "A confounder is a common cause of both the exposure and outcome that can create or distort their observed association. A variable is not a confounder merely because it correlates with both; the causal structure matters. Randomization balances confounders in expectation, while observational studies need a defensible adjustment strategy.",
    signals: ["Common cause", "Distorted association", "Causal structure", "Adjustment"],
    trap: "Controlling for every available variable, including mediators or colliders that can introduce bias.",
    followUp: "How would a causal diagram help decide whether to adjust for a variable?",
    priority: "Build",
    answerSeconds: 45,
  },
  {
    id: "rapid-ds-ab-randomization",
    category: "Data science rapid fire",
    question: "Why is randomization important in an A/B test?",
    answer: "Random assignment makes treatment independent of pre-treatment characteristics in expectation, supporting a causal comparison between groups. It does not guarantee balance in one finite experiment or fix attrition, interference, logging errors or noncompliance. Validate assignment and analyze users according to the predeclared experimental unit and estimand.",
    signals: ["Exchangeable groups", "Causal comparison", "Finite imbalance", "Experiment integrity"],
    trap: "Assuming a randomized flag makes biased exposure, sample-ratio mismatch or cross-user interference irrelevant.",
    followUp: "What does sample-ratio mismatch suggest, and why should it block interpretation?",
    priority: "Core",
    answerSeconds: 45,
  },
  {
    id: "rapid-ds-simpsons-paradox",
    category: "Data science rapid fire",
    question: "What is Simpson's paradox?",
    answer: "Simpson's paradox occurs when an aggregate association reverses or disappears after data is split into meaningful groups. It arises because group composition and a lurking variable influence the aggregate. The lesson is not to segment everything blindly, but to define the causal question and inspect important pre-specified cohorts.",
    signals: ["Aggregate reversal", "Group composition", "Lurking variable", "Causal question"],
    trap: "Choosing whichever aggregation supports the preferred conclusion without a principled reason for conditioning.",
    followUp: "How could a product metric improve overall while worsening within every customer segment?",
    priority: "Build",
    answerSeconds: 45,
  },
  {
    id: "rapid-ds-missingness",
    category: "Data science rapid fire",
    question: "What are MCAR, MAR and MNAR missing data?",
    answer: "MCAR means missingness is unrelated to observed or unobserved values. MAR means it can depend on observed variables, while MNAR means it still depends on the missing value or other unobserved information after conditioning. The mechanism determines whether deletion or imputation is unbiased, and MNAR usually requires sensitivity analysis or stronger data collection.",
    signals: ["Missing completely at random", "Observed dependence", "Unobserved dependence", "Sensitivity analysis"],
    trap: "Treating all missing values as zero or assuming imputation automatically removes missingness bias.",
    followUp: "Why might missing income in a credit application be MNAR?",
    priority: "Build",
    answerSeconds: 45,
  },
];
