export type Week = {
  week: number;
  phase: string;
  title: string;
  focus: string;
  outcome: string;
  topics: string[];
};

export type Card = {
  id: string;
  category: string;
  question: string;
  answer: string;
  signals: string[];
  trap: string;
  followUp: string;
  priority: "Core" | "Build" | "Advanced";
};

export const weeks: Week[] = [
  {
    week: 1,
    phase: "Foundation",
    title: "Positioning, Python & SQL",
    focus: "Build the 90-second introduction and clear basic screens.",
    outcome: "Deliver “Tell me about yourself” cleanly, solve one Python and one SQL problem.",
    topics: ["Project stories", "Data structures", "Complexity", "Window functions", "NULL semantics"],
  },
  {
    week: 2,
    phase: "Foundation",
    title: "ML fundamentals",
    focus: "Reason about models, metrics, validation and production failure.",
    outcome: "Explain the AML model for 10 minutes with tradeoffs and monitoring.",
    topics: ["Logistic regression", "Trees", "Imbalance", "Leakage", "Drift"],
  },
  {
    week: 3,
    phase: "LLM core",
    title: "LLMs & structured output",
    focus: "Connect tokens, embeddings, attention, prompting and tool use.",
    outcome: "Explain structured output vs function calling with a production example.",
    topics: ["Tokenization", "Embeddings", "Attention", "Prompting", "Schema validation"],
  },
  {
    week: 4,
    phase: "LLM core",
    title: "RAG deep dive",
    focus: "Trace the full path from document ingestion to cited answer.",
    outcome: "Design internal document Q&A for 30 minutes without losing structure.",
    topics: ["Chunking", "Hybrid search", "Re-ranking", "Citations", "Permissions"],
  },
  {
    week: 5,
    phase: "Production AI",
    title: "Evaluation, safety & observability",
    focus: "Prove quality, trace failures and control privacy and cost.",
    outcome: "Present an eval strategy that separates retrieval from generation quality.",
    topics: ["Golden sets", "Faithfulness", "Tracing", "Prompt injection", "Cost"],
  },
  {
    week: 6,
    phase: "Production AI",
    title: "AWS, SageMaker & LLMOps",
    focus: "Turn cloud knowledge into a production inference story.",
    outcome: "Design a real-time ML recommendation API on AWS for 30 minutes.",
    topics: ["Lambda", "SageMaker", "IAM", "CI/CD", "Rollback"],
  },
  {
    week: 7,
    phase: "System design",
    title: "ML system design",
    focus: "Structure recommendation, scoring and monitoring systems.",
    outcome: "Design a recommendation system and make explicit tradeoffs.",
    topics: ["Candidates", "Ranking", "Feature store", "Feedback loops", "A/B tests"],
  },
  {
    week: 8,
    phase: "System design",
    title: "LLM system design",
    focus: "Design secure, evaluated, multi-user LLM products.",
    outcome: "Design an enterprise RAG platform for 45 minutes.",
    topics: ["Ingestion", "Gateway", "Tools", "Evaluation", "Security"],
  },
  {
    week: 9,
    phase: "Advanced",
    title: "Fine-tuning & inference",
    focus: "Know enough model adaptation and serving to reason clearly.",
    outcome: "Compare RAG, fine-tuning and LoRA with concrete decision criteria.",
    topics: ["LoRA", "QLoRA", "Quantization", "Batching", "KV cache"],
  },
  {
    week: 10,
    phase: "Performance",
    title: "Mock interview week",
    focus: "Convert knowledge into consistent spoken performance.",
    outcome: "Complete behavioral, ML, LLM and system-design loops without freezing.",
    topics: ["Behavioral", "ML", "Python + SQL", "LLM", "System design"],
  },
];

export const cards: Card[] = [
  {
    id: "intro",
    category: "Positioning",
    question: "Tell me about yourself.",
    answer: "Use a present–past–future arc. Start with the engineering identity relevant to the role, prove it with two high-signal projects, then explain why this role is the logical next step. Keep biography out; make every sentence evidence for fit.",
    signals: ["90 seconds", "Current value", "2 proof points", "Role-specific close"],
    trap: "Reciting a chronological résumé or claiming passion without evidence.",
    followUp: "Which project best proves you can ship an AI system, not just prototype one?",
    priority: "Core",
  },
  {
    id: "python-dict",
    category: "Python + SQL",
    question: "How does a Python dict work, and what are its complexity limits?",
    answer: "A dict is a hash table mapping hashable keys to values. Lookup, insertion and deletion are O(1) on average because the key hash selects a slot; collisions are resolved internally. Worst case is O(n), and resizing has occasional cost. Keys must have stable hash/equality behavior.",
    signals: ["Hash table", "Average O(1)", "Collisions", "Hashable keys"],
    trap: "Saying operations are always O(1), or confusing insertion order with sorted order.",
    followUp: "Why can a tuple be a key while a list cannot?",
    priority: "Core",
  },
  {
    id: "generator",
    category: "Python + SQL",
    question: "What is a Python generator, and when would you use one?",
    answer: "A generator is a lazy iterator whose state is suspended at yield. It produces one value at a time, which makes streaming large or unbounded data memory-efficient. The tradeoff is one-pass consumption and less convenient random access or debugging.",
    signals: ["Lazy", "yield", "Stateful iteration", "Memory tradeoff"],
    trap: "Only saying it saves memory without explaining laziness or one-pass behavior.",
    followUp: "How would you safely stream a large file through a transformation pipeline?",
    priority: "Core",
  },
  {
    id: "sql-latest",
    category: "Python + SQL",
    question: "Write SQL to return the latest record per customer.",
    answer: "Rank records inside each customer partition, then keep rank one: ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY event_time DESC, record_id DESC). The second ordering key makes ties deterministic. QUALIFY can filter directly where supported; otherwise use a CTE.",
    signals: ["ROW_NUMBER", "PARTITION BY", "Deterministic tie-break", "CTE or QUALIFY"],
    trap: "Joining to MAX(timestamp) and accidentally returning duplicate tied rows.",
    followUp: "How would the query change if tied latest records must all be retained?",
    priority: "Core",
  },
  {
    id: "logistic",
    category: "ML fundamentals",
    question: "Explain logistic regression and why it outputs probabilities.",
    answer: "Logistic regression models the log-odds of a binary outcome as a linear function of features. The sigmoid maps that unbounded score into 0–1. Training typically minimizes log loss. The threshold is a business decision, while regularization controls complexity and correlated/noisy features.",
    signals: ["Log-odds", "Sigmoid", "Log loss", "Threshold tradeoff"],
    trap: "Calling it regression because of the name, or treating 0.5 as a universal threshold.",
    followUp: "Why might a well-ranked model still have poorly calibrated probabilities?",
    priority: "Core",
  },
  {
    id: "auc",
    category: "ML fundamentals",
    question: "When is PR-AUC more useful than ROC-AUC?",
    answer: "ROC-AUC measures ranking across true- and false-positive rates and can look optimistic when negatives dominate. PR-AUC focuses on precision and recall for the positive class, so it is more informative for rare-event problems such as fraud or AML. Always relate the metric to operating thresholds and error costs.",
    signals: ["Class imbalance", "Positive class", "Error cost", "Threshold"],
    trap: "Choosing a metric by convention without connecting it to prevalence and decisions.",
    followUp: "How would you select a threshold for an AML review queue with fixed capacity?",
    priority: "Core",
  },
  {
    id: "leakage",
    category: "ML fundamentals",
    question: "What is feature leakage, and how do you detect it?",
    answer: "Leakage occurs when training features contain information unavailable at prediction time or derived from the target. It creates unrealistically strong offline results. Prevent it with point-in-time joins, time-based splits, lineage review, feature availability tests and suspicious-feature ablations.",
    signals: ["Prediction-time availability", "Target proxy", "Point-in-time join", "Ablation"],
    trap: "Treating leakage as ordinary overfitting; leakage invalidates the evaluation itself.",
    followUp: "Give an AML feature that might accidentally leak a downstream investigation outcome.",
    priority: "Core",
  },
  {
    id: "drift",
    category: "ML fundamentals",
    question: "How would you monitor a model in production?",
    answer: "Monitor service health, inputs, predictions and delayed outcomes separately. Track latency/errors, schema and missingness, feature/prediction drift, calibration and task metrics once labels arrive. Slice by important cohorts, define action thresholds, and connect alerts to rollback or retraining—not dashboards alone.",
    signals: ["Four layers", "Cohort slices", "Delayed labels", "Actionable alerts"],
    trap: "Equating input drift with model failure or proposing retraining without diagnosis.",
    followUp: "What can you monitor before labels become available?",
    priority: "Core",
  },
  {
    id: "embedding",
    category: "LLM core",
    question: "What is an embedding, and why does cosine similarity work?",
    answer: "An embedding maps an item into a dense vector learned so related items occupy nearby regions. Cosine similarity compares vector direction rather than magnitude, often serving as a useful semantic-nearness proxy. Its quality depends on the embedding model, domain, text representation and retrieval corpus.",
    signals: ["Dense vector", "Learned geometry", "Direction", "Domain dependence"],
    trap: "Claiming cosine similarity measures truth or guarantees semantic relevance.",
    followUp: "When would dot product or a cross-encoder be preferable?",
    priority: "Core",
  },
  {
    id: "attention",
    category: "LLM core",
    question: "Explain self-attention without hand-waving.",
    answer: "Each token produces query, key and value vectors. Query–key scores determine how much that token should attend to other positions; a softmax normalizes the scores and the weighted values form the new representation. Multiple heads learn different relationships, while positional information preserves order.",
    signals: ["Q/K/V", "Scaled scores", "Weighted values", "Position"],
    trap: "Describing attention as a vague focus mechanism without the computation.",
    followUp: "Why does standard attention become expensive for long contexts?",
    priority: "Build",
  },
  {
    id: "structured-tools",
    category: "LLM core",
    question: "Structured output vs function calling: what is the difference?",
    answer: "Structured output constrains the model’s response to a schema when the application needs typed data. Function calling lets the model select an application-defined capability and propose its arguments; the application still validates, authorizes and executes it. Tool calling therefore crosses a side-effect boundary that plain structured extraction does not.",
    signals: ["Schema", "Capability selection", "App executes", "Authorization boundary"],
    trap: "Letting model-provided arguments bypass validation or treating a tool call as execution.",
    followUp: "How would you make a money-transfer tool safe?",
    priority: "Core",
  },
  {
    id: "hallucination",
    category: "LLM core",
    question: "Why do LLMs hallucinate, and how do you reduce it?",
    answer: "An LLM predicts plausible continuations; it is not inherently checking claims against a source of truth. Reduce unsupported answers through retrieval quality, explicit grounding and abstention, constrained outputs, tool use for facts, citation verification and task-specific evaluation. No prompt can guarantee zero hallucination.",
    signals: ["Next-token objective", "Grounding", "Abstention", "Evaluation"],
    trap: "Promising that temperature zero or a stronger system prompt eliminates hallucination.",
    followUp: "How would you measure whether citations actually support the answer?",
    priority: "Core",
  },
  {
    id: "rag",
    category: "RAG",
    question: "What is RAG, and when is it better than fine-tuning?",
    answer: "RAG retrieves external evidence at request time and places it in the model context. It fits changing, private or citation-critical knowledge because documents can be refreshed and inspected without changing model weights. Fine-tuning is better for stable behavior, style or task adaptation—not as a general document database.",
    signals: ["Retrieve then generate", "Fresh/private knowledge", "Citations", "Behavior vs knowledge"],
    trap: "Framing RAG and fine-tuning as mutually exclusive or assuming retrieval guarantees grounding.",
    followUp: "When would you combine RAG with a fine-tuned model?",
    priority: "Core",
  },
  {
    id: "chunking",
    category: "RAG",
    question: "How do you choose chunk size and overlap?",
    answer: "Start from document structure and the smallest unit that answers a likely question, not an arbitrary token count. Too small loses context; too large dilutes relevance and wastes context. Use heading-aware chunks, preserve metadata and measure retrieval/answer quality across candidate settings. Overlap is a fallback for boundary loss, not free quality.",
    signals: ["Semantic unit", "Context vs precision", "Metadata", "Empirical evaluation"],
    trap: "Quoting one universal chunk size or adding large overlap without cost analysis.",
    followUp: "How would you chunk tables, policies and source code differently?",
    priority: "Core",
  },
  {
    id: "hybrid-rerank",
    category: "RAG",
    question: "Why use hybrid search and re-ranking?",
    answer: "Dense retrieval captures semantic similarity while lexical retrieval excels at exact terms, identifiers and rare names. Hybrid search combines their candidates. A slower cross-encoder or learned reranker then scores query–document pairs more precisely, improving top-k quality while keeping latency bounded.",
    signals: ["Dense + lexical", "Candidate recall", "Cross-encoder", "Latency tradeoff"],
    trap: "Using a reranker to compensate for broken ingestion or permission filtering.",
    followUp: "At what stage must access-control filtering happen?",
    priority: "Build",
  },
  {
    id: "rag-eval",
    category: "Evaluation",
    question: "How do you evaluate a RAG system?",
    answer: "Separate the pipeline. Evaluate retrieval with hit/recall@k and ranking metrics against expected evidence. Evaluate generation for correctness, faithfulness, citation support, relevance and abstention. Add end-to-end task success, latency and cost. Use a representative golden set, slices and human review; treat LLM judges as noisy instruments.",
    signals: ["Retrieval vs generation", "Golden set", "Slices", "Human calibration"],
    trap: "Reporting only answer similarity or one aggregate score, which hides retrieval failures.",
    followUp: "How would you diagnose a fluent wrong answer with correct documents retrieved?",
    priority: "Core",
  },
  {
    id: "prompt-regression",
    category: "Evaluation",
    question: "How do you safely ship a prompt change?",
    answer: "Version the prompt and run it on a frozen representative eval set. Compare quality, safety, latency and token cost by slice; inspect regressions, then canary a small share of production traffic with traceability and a rollback path. Online A/B tests measure user impact after offline gates pass.",
    signals: ["Versioning", "Frozen eval set", "Slice regressions", "Canary + rollback"],
    trap: "Judging a change from a handful of hand-picked examples.",
    followUp: "What data would you log so a bad answer can be reproduced?",
    priority: "Core",
  },
  {
    id: "injection",
    category: "Evaluation",
    question: "How do you defend against prompt injection in RAG?",
    answer: "Treat retrieved text and tool outputs as untrusted data, not instructions. Separate system policy from content, restrict tools with least privilege, validate arguments, require confirmation for high-impact actions, filter results by authorization before generation and test adversarial cases. Detection helps, but the security boundary must not depend on the model obeying.",
    signals: ["Untrusted content", "Least privilege", "Authorization outside model", "Adversarial evals"],
    trap: "Relying on a prompt that says ‘ignore malicious instructions.’",
    followUp: "What changes when the assistant can only answer versus take actions?",
    priority: "Core",
  },
  {
    id: "lambda-sagemaker",
    category: "Cloud + MLOps",
    question: "SageMaker endpoint vs Lambda for inference: how do you decide?",
    answer: "Lambda is good for short, stateless orchestration with strict runtime, package and memory limits. A managed model endpoint fits heavier artifacts, specialized containers, accelerators, predictable throughput and model-centric deployment controls. A common design uses API Gateway and Lambda for auth/validation, then SageMaker for inference.",
    signals: ["Workload constraints", "Orchestration vs serving", "Scaling", "Operational tradeoff"],
    trap: "Choosing by product name rather than latency, payload, model size and traffic shape.",
    followUp: "How would you handle cold starts and a sudden traffic spike?",
    priority: "Build",
  },
  {
    id: "ml-cicd",
    category: "Cloud + MLOps",
    question: "Design CI/CD and rollback for an ML model.",
    answer: "Version code, data lineage, features, model artifact and evaluation report. CI validates contracts and reproducibility; CD promotes an immutable candidate through offline gates, shadow/canary traffic and monitored rollout. Keep the previous model and feature contract deployable, define rollback triggers, and separate model approval from application release where needed.",
    signals: ["Full lineage", "Immutable artifact", "Canary", "Rollback contract"],
    trap: "Treating a model like ordinary code while ignoring data and statistical validation.",
    followUp: "What makes a rollback unsafe when feature pipelines have also changed?",
    priority: "Build",
  },
  {
    id: "recommendation",
    category: "System design",
    question: "Design a recommendation system.",
    answer: "Clarify objective and constraints; define events and labels. Use broad candidate generation followed by a richer ranking model, then business-rule and diversity filters. Separate offline training from low-latency serving, keep online/offline features consistent, log exposure for unbiased evaluation, and monitor quality, latency, drift and feedback loops.",
    signals: ["Objective", "Candidates → ranking", "Feature consistency", "Exposure logging"],
    trap: "Jumping to a model before defining success, feedback bias and serving constraints.",
    followUp: "How would you solve cold start for new users and new items?",
    priority: "Core",
  },
  {
    id: "enterprise-rag",
    category: "System design",
    question: "Design an enterprise RAG platform.",
    answer: "Start with users, sources, freshness and permission requirements. Build source-specific ingestion into parsed, versioned chunks with metadata and ACLs; create hybrid retrieval with authorization filtering and optional reranking; assemble grounded prompts through an LLM gateway; validate citations and outputs; then add evals, traces, cost controls, deletion/refresh workflows and failure fallbacks.",
    signals: ["Requirements first", "ACL-aware ingestion/retrieval", "Gateway", "Eval + operations"],
    trap: "Drawing vector DB → LLM and omitting tenancy, refresh, deletion, evaluation and failure modes.",
    followUp: "How do you prevent a user from inferring that a restricted document exists?",
    priority: "Core",
  },
  {
    id: "llm-gateway",
    category: "System design",
    question: "What belongs in an LLM gateway?",
    answer: "A gateway centralizes provider abstraction, model routing, authentication, policy, quotas, prompt/model versions, retries and fallbacks, redaction, telemetry and cost controls. It should not hide every provider difference or become a monolith; preserve typed capability contracts and let applications own domain behavior and final authorization.",
    signals: ["Cross-cutting policy", "Routing", "Observability", "Typed capabilities"],
    trap: "Putting business logic in the gateway or assuming all providers are interchangeable.",
    followUp: "How would you route requests across models without silently changing quality?",
    priority: "Build",
  },
  {
    id: "agent-tools",
    category: "System design",
    question: "Design an AI agent that calls internal APIs safely.",
    answer: "Expose a small typed tool set behind ordinary authorization. The model proposes a plan and arguments; deterministic code validates identity, permissions, schemas, rate limits and preconditions. Separate read from write tools, require confirmation for consequential actions, make writes idempotent, cap loops and budgets, and trace every decision and tool result.",
    signals: ["Model proposes", "Code authorizes", "Confirmation", "Idempotency + limits"],
    trap: "Granting broad API credentials to the model or letting natural language define permissions.",
    followUp: "How would you recover after the tool succeeds but the agent times out?",
    priority: "Build",
  },
  {
    id: "lora",
    category: "Advanced LLM",
    question: "Explain LoRA and QLoRA.",
    answer: "LoRA freezes the base model and learns small low-rank update matrices for selected weights, reducing trainable parameters and memory. QLoRA also stores the frozen base in low precision while training LoRA adapters, reducing memory further. They lower adaptation cost, but data quality, evaluation and serving complexity still matter.",
    signals: ["Frozen base", "Low-rank adapters", "Quantized base", "Operational tradeoff"],
    trap: "Claiming LoRA is equivalent to full fine-tuning or always matches its quality.",
    followUp: "When would RAG still be necessary after LoRA tuning?",
    priority: "Advanced",
  },
  {
    id: "quantization",
    category: "Advanced LLM",
    question: "What is quantization, and what can go wrong?",
    answer: "Quantization represents weights—and sometimes activations or KV cache—with fewer bits to reduce memory bandwidth, footprint and often latency. Accuracy can degrade, especially for sensitive layers or tasks; hardware kernels and calibration matter. Evaluate task quality and throughput on the actual serving stack rather than assuming lower bits are faster.",
    signals: ["Lower precision", "Memory bandwidth", "Quality risk", "Hardware-specific benchmark"],
    trap: "Equating model size reduction with guaranteed end-to-end speedup.",
    followUp: "What is the difference between post-training quantization and quantization-aware training?",
    priority: "Advanced",
  },
  {
    id: "kv-cache",
    category: "Advanced LLM",
    question: "What is the KV cache, and why does it matter for inference?",
    answer: "During autoregressive decoding, attention needs keys and values from previous tokens. Caching them avoids recomputing the whole prefix for every new token, greatly reducing decode work. The cache grows with sequence length, batch size, layers and hidden dimensions, so it becomes a major memory and concurrency constraint.",
    signals: ["Autoregressive decode", "Reuse K/V", "Latency", "Memory/concurrency"],
    trap: "Saying it caches answers or eliminates the quadratic prefill cost.",
    followUp: "Why can batching improve throughput while hurting latency?",
    priority: "Advanced",
  },
];

export const readinessGate = [
  "Tell me about yourself.",
  "Why AI / LLM engineering?",
  "Explain your LLM platform architecture.",
  "What is RAG?",
  "Why RAG instead of fine-tuning?",
  "How do you evaluate a RAG system?",
  "How do you reduce hallucination?",
  "Explain your Scotiabank AML model.",
  "Design a document Q&A system.",
  "Design a recommendation / ranking system.",
];

export const projectStories = [
  {
    name: "Fleet enterprise LLM / RAG platform",
    proof: "Architecture, ingestion, retrieval, gateway, evaluation, security and observability.",
    structure: ["Why platform", "Architecture", "Retrieval", "Evaluation", "Security", "Tradeoffs"],
  },
  {
    name: "Scotiabank AML risk model",
    proof: "ML judgment under imbalance, explainability and regulatory constraints.",
    structure: ["Business risk", "Data", "Model choice", "Evaluation", "Explainability", "Impact"],
  },
  {
    name: "Crew recommendation on SageMaker",
    proof: "Production ranking, cloud boundaries, latency, monitoring and failure handling.",
    structure: ["Objective", "Why ranking", "Contracts", "Serving", "Monitoring", "Improvements"],
  },
];

export const cadence = [
  ["MON", "ML fundamentals", "5 answers out loud"],
  ["TUE", "LLM / RAG", "Notes + 5 answers"],
  ["WED", "Python + SQL", "1 coding + 1 SQL"],
  ["THU", "System design", "Draw + explain"],
  ["FRI", "Project deep dive", "1 story rehearsal"],
  ["SAT", "Mock interview", "60–90 minutes"],
  ["SUN", "Repair", "Rewrite weak answers"],
];

export const systemDesignFrames = {
  "ML system": [
    "Clarify requirements", "Users + objective", "Input / output", "Architecture", "Data + features",
    "Model choice", "Training", "Serving", "Monitoring", "Failures", "Tradeoffs", "Next step",
  ],
  "LLM system": [
    "Use case + users", "Permissions", "Sources", "Ingestion", "Chunking", "Retrieval", "Prompt assembly",
    "Gateway + tools", "Validation + citations", "Evaluation", "Monitoring", "Security", "Cost", "Failures",
  ],
};
