import { extraCards } from "./extra-cards";
import { dataEngineeringCards } from "./data-engineering-cards";
import { codingCards } from "./coding-cards";
import { rapidFireCards } from "./rapid-fire-cards";
import { moxInterviewCards } from "./mox-interview-cards";
import { moxPythonCards } from "./mox-python-cards";
import { hkexAwsBasicCards } from "./hkex-aws-basic-cards";
import { hkexAwsAdvancedCards } from "./hkex-aws-advanced-cards";
import { hkexSqlIntermediateCards } from "./hkex-sql-intermediate-cards";
import { hkexSqlAdvancedCards } from "./hkex-sql-advanced-cards";
import { hkexProblemSolvingBasicCards } from "./hkex-problem-solving-basic-cards";
import { hkexProblemSolvingAdvancedCards } from "./hkex-problem-solving-advanced-cards";
import { hkexSyllabusAwsSqlCards } from "./hkex-syllabus-aws-sql-cards";
import { hkexSyllabusProblemSolvingCards } from "./hkex-syllabus-problem-solving-cards";
import { hkexInterviewCards } from "./hkex-interview-cards";
import { cmbiDataAgentCards } from "./cmbi-data-agent-cards";

export type Week = {
  week: number;
  phase: string;
  title: string;
  focus: string;
  outcome: string;
  topics: string[];
};

export type Card = {
  id: string;
  category: string;
  question: string;
  code?: string;
  answerSeconds?: number;
  answer: string;
  signals: string[];
  trap: string;
  followUp: string;
  priority: "Core" | "Build" | "Advanced";
};

export const weeks: Week[] = [
  {
    week: 1,
    phase: "Foundation",
    title: "Positioning, Python & SQL",
    focus: "Build the 90-second introduction and clear basic screens.",
    outcome: "Deliver “Tell me about yourself” cleanly, solve one Python and one SQL problem.",
    topics: ["Project stories", "Data structures", "Complexity", "Window functions", "NULL semantics"],
  },
  {
    week: 2,
    phase: "Foundation",
    title: "ML fundamentals",
    focus: "Reason about models, metrics, validation and production failure.",
    outcome: "Explain the AML model for 10 minutes with tradeoffs and monitoring.",
    topics: ["Logistic regression", "Trees", "Imbalance", "Leakage", "Drift"],
  },
  {
    week: 3,
    phase: "LLM core",
    title: "LLMs & structured output",
    focus: "Connect tokens, embeddings, attention, prompting and tool use.",
    outcome: "Explain structured output vs function calling with a production example.",
    topics: ["Tokenization", "Embeddings", "Attention", "Prompting", "Schema validation"],
  },
  {
    week: 4,
    phase: "LLM core",
    title: "RAG deep dive",
    focus: "Trace the full path from document ingestion to cited answer.",
    outcome: "Design internal document Q&A for 30 minutes without losing structure.",
    topics: ["Chunking", "Hybrid search", "Re-ranking", "Citations", "Permissions"],
  },
  {
    week: 5,
    phase: "Production AI",
    title: "Evaluation, safety & observability",
    focus: "Prove quality, trace failures and control privacy and cost.",
    outcome: "Present an eval strategy that separates retrieval from generation quality.",
    topics: ["Golden sets", "Faithfulness", "Tracing", "Prompt injection", "Cost"],
  },
  {
    week: 6,
    phase: "Production AI",
    title: "AWS, SageMaker & LLMOps",
    focus: "Turn cloud knowledge into a production inference story.",
    outcome: "Design a real-time ML recommendation API on AWS for 30 minutes.",
    topics: ["Lambda", "SageMaker", "IAM", "CI/CD", "Rollback"],
  },
  {
    week: 7,
    phase: "System design",
    title: "ML system design",
    focus: "Structure recommendation, scoring and monitoring systems.",
    outcome: "Design a recommendation system and make explicit tradeoffs.",
    topics: ["Candidates", "Ranking", "Feature store", "Feedback loops", "A/B tests"],
  },
  {
    week: 8,
    phase: "System design",
    title: "LLM system design",
    focus: "Design secure, evaluated, multi-user LLM products.",
    outcome: "Design an enterprise RAG platform for 45 minutes.",
    topics: ["Ingestion", "Gateway", "Tools", "Evaluation", "Security"],
  },
  {
    week: 9,
    phase: "Advanced",
    title: "Fine-tuning & inference",
    focus: "Know enough model adaptation and serving to reason clearly.",
    outcome: "Compare RAG, fine-tuning and LoRA with concrete decision criteria.",
    topics: ["LoRA", "QLoRA", "Quantization", "Batching", "KV cache"],
  },
  {
    week: 10,
    phase: "Performance",
    title: "Mock interview week",
    focus: "Convert knowledge into consistent spoken performance.",
    outcome: "Complete behavioral, ML, LLM and system-design loops without freezing.",
    topics: ["Behavioral", "ML", "Python + SQL", "LLM", "System design"],
  },
];

const coreCards: Card[] = [
  {
    id: "intro",
    category: "Positioning",
    question: "Tell me about yourself.",
    answer: "Use a present–past–future arc. Start with the engineering identity relevant to the role, prove it with two high-signal projects, then explain why this role is the logical next step. Keep biography out; make every sentence evidence for fit.",
    signals: ["90 seconds", "Current value", "2 proof points", "Role-specific close"],
    trap: "Reciting a chronological résumé or claiming passion without evidence.",
    followUp: "Which project best proves you can ship an AI system, not just prototype one?",
    priority: "Core",
  },
  {
    id: "python-dict",
    category: "Python + SQL",
    question: "How does a Python dict work, and what are its complexity limits?",
    answer: "A dict is a hash table mapping hashable keys to values. Lookup, insertion and deletion are O(1) on average because the key hash selects a slot; collisions are resolved internally. Worst case is O(n), and resizing has occasional cost. Keys must have stable hash/equality behavior.",
    signals: ["Hash table", "Average O(1)", "Collisions", "Hashable keys"],
    trap: "Saying operations are always O(1), or confusing insertion order with sorted order.",
    followUp: "Why can a tuple be a key while a list cannot?",
    priority: "Core",
  },
  {
    id: "generator",
    category: "Python + SQL",
    question: "What is a Python generator, and when would you use one?",
    answer: "A generator is a lazy iterator whose state is suspended at yield. It produces one value at a time, which makes streaming large or unbounded data memory-efficient. The tradeoff is one-pass consumption and less convenient random access or debugging.",
    signals: ["Lazy", "yield", "Stateful iteration", "Memory tradeoff"],
    trap: "Only saying it saves memory without explaining laziness or one-pass behavior.",
    followUp: "How would you safely stream a large file through a transformation pipeline?",
    priority: "Core",
  },
  {
    id: "sql-latest",
    category: "Python + SQL",
    question: "Write SQL to return the latest record per customer.",
    answer: "Rank records inside each customer partition, then keep rank one: ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY event_time DESC, record_id DESC). The second ordering key makes ties deterministic. QUALIFY can filter directly where supported; otherwise use a CTE.",
    signals: ["ROW_NUMBER", "PARTITION BY", "Deterministic tie-break", "CTE or QUALIFY"],
    trap: "Joining to MAX(timestamp) and accidentally returning duplicate tied rows.",
    followUp: "How would the query change if tied latest records must all be retained?",
    priority: "Core",
  },
  {
    id: "logistic",
    category: "ML fundamentals",
    question: "Explain logistic regression and why it outputs probabilities.",
    answer: "Logistic regression models the log-odds of a binary outcome as a linear function of features. The sigmoid maps that unbounded score into 0–1. Training typically minimizes log loss. The threshold is a business decision, while regularization controls complexity and correlated/noisy features.",
    signals: ["Log-odds", "Sigmoid", "Log loss", "Threshold tradeoff"],
    trap: "Calling it regression because of the name, or treating 0.5 as a universal threshold.",
    followUp: "Why might a well-ranked model still have poorly calibrated probabilities?",
    priority: "Core",
  },
  {
    id: "auc",
    category: "ML fundamentals",
    question: "When is PR-AUC more useful than ROC-AUC?",
    answer: "ROC-AUC measures ranking across true- and false-positive rates and can look optimistic when negatives dominate. PR-AUC focuses on precision and recall for the positive class, so it is more informative for rare-event problems such as fraud or AML. Always relate the metric to operating thresholds and error costs.",
    signals: ["Class imbalance", "Positive class", "Error cost", "Threshold"],
    trap: "Choosing a metric by convention without connecting it to prevalence and decisions.",
    followUp: "How would you select a threshold for an AML review queue with fixed capacity?",
    priority: "Core",
  },
  {
    id: "leakage",
    category: "ML fundamentals",
    question: "What is feature leakage, and how do you detect it?",
    answer: "Leakage occurs when training features contain information unavailable at prediction time or derived from the target. It creates unrealistically strong offline results. Prevent it with point-in-time joins, time-based splits, lineage review, feature availability tests and suspicious-feature ablations.",
    signals: ["Prediction-time availability", "Target proxy", "Point-in-time join", "Ablation"],
    trap: "Treating leakage as ordinary overfitting; leakage invalidates the evaluation itself.",
    followUp: "Give an AML feature that might accidentally leak a downstream investigation outcome.",
    priority: "Core",
  },
  {
    id: "drift",
    category: "ML fundamentals",
    question: "How would you monitor a model in production?",
    answer: "Monitor service health, inputs, predictions and delayed outcomes separately. Track latency/errors, schema and missingness, feature/prediction drift, calibration and task metrics once labels arrive. Slice by important cohorts, define action thresholds, and connect alerts to rollback or retraining—not dashboards alone.",
    signals: ["Four layers", "Cohort slices", "Delayed labels", "Actionable alerts"],
    trap: "Equating input drift with model failure or proposing retraining without diagnosis.",
    followUp: "What can you monitor before labels become available?",
    priority: "Core",
  },
  {
    id: "embedding",
    category: "LLM core",
    question: "What is an embedding, and why does cosine similarity work?",
    answer: "An embedding maps an item into a dense vector learned so related items occupy nearby regions. Cosine similarity compares vector direction rather than magnitude, often serving as a useful semantic-nearness proxy. Its quality depends on the embedding model, domain, text representation and retrieval corpus.",
    signals: ["Dense vector", "Learned geometry", "Direction", "Domain dependence"],
    trap: "Claiming cosine similarity measures truth or guarantees semantic relevance.",
    followUp: "When would dot product or a cross-encoder be preferable?",
    priority: "Core",
  },
  {
    id: "attention",
    category: "LLM core",
    question: "Explain self-attention without hand-waving.",
    answer: "Each token produces query, key and value vectors. Query–key scores determine how much that token should attend to other positions; a softmax normalizes the scores and the weighted values form the new representation. Multiple heads learn different relationships, while positional information preserves order.",
    signals: ["Q/K/V", "Scaled scores", "Weighted values", "Position"],
    trap: "Describing attention as a vague focus mechanism without the computation.",
    followUp: "Why does standard attention become expensive for long contexts?",
    priority: "Build",
  },
  {
    id: "structured-tools",
    category: "LLM core",
    question: "Structured output vs function calling: what is the difference?",
    answer: "Structured output constrains the model’s response to a schema when the application needs typed data. Function calling lets the model select an application-defined capability and propose its arguments; the application still validates, authorizes and executes it. Tool calling therefore crosses a side-effect boundary that plain structured extraction does not.",
    signals: ["Schema", "Capability selection", "App executes", "Authorization boundary"],
    trap: "Letting model-provided arguments bypass validation or treating a tool call as execution.",
    followUp: "How would you make a money-transfer tool safe?",
    priority: "Core",
  },
  {
    id: "hallucination",
    category: "LLM core",
    question: "Why do LLMs hallucinate, and how do you reduce it?",
    answer: "An LLM predicts plausible continuations; it is not inherently checking claims against a source of truth. Reduce unsupported answers through retrieval quality, explicit grounding and abstention, constrained outputs, tool use for facts, citation verification and task-specific evaluation. No prompt can guarantee zero hallucination.",
    signals: ["Next-token objective", "Grounding", "Abstention", "Evaluation"],
    trap: "Promising that temperature zero or a stronger system prompt eliminates hallucination.",
    followUp: "How would you measure whether citations actually support the answer?",
    priority: "Core",
  },
  {
    id: "rag",
    category: "RAG",
    question: "What is RAG, and when is it better than fine-tuning?",
    answer: "RAG retrieves external evidence at request time and places it in the model context. It fits changing, private or citation-critical knowledge because documents can be refreshed and inspected without changing model weights. Fine-tuning is better for stable behavior, style or task adaptation—not as a general document database.",
    signals: ["Retrieve then generate", "Fresh/private knowledge", "Citations", "Behavior vs knowledge"],
    trap: "Framing RAG and fine-tuning as mutually exclusive or assuming retrieval guarantees grounding.",
    followUp: "When would you combine RAG with a fine-tuned model?",
    priority: "Core",
  },
  {
    id: "chunking",
    category: "RAG",
    question: "How do you choose chunk size and overlap?",
    answer: "Start from document structure and the smallest unit that answers a likely question, not an arbitrary token count. Too small loses context; too large dilutes relevance and wastes context. Use heading-aware chunks, preserve metadata and measure retrieval/answer quality across candidate settings. Overlap is a fallback for boundary loss, not free quality.",
    signals: ["Semantic unit", "Context vs precision", "Metadata", "Empirical evaluation"],
    trap: "Quoting one universal chunk size or adding large overlap without cost analysis.",
    followUp: "How would you chunk tables, policies and source code differently?",
    priority: "Core",
  },
  {
    id: "hybrid-rerank",
    category: "RAG",
    question: "Why use hybrid search and re-ranking?",
    answer: "Dense retrieval captures semantic similarity while lexical retrieval excels at exact terms, identifiers and rare names. Hybrid search combines their candidates. A slower cross-encoder or learned reranker then scores query–document pairs more precisely, improving top-k quality while keeping latency bounded.",
    signals: ["Dense + lexical", "Candidate recall", "Cross-encoder", "Latency tradeoff"],
    trap: "Using a reranker to compensate for broken ingestion or permission filtering.",
    followUp: "At what stage must access-control filtering happen?",
    priority: "Build",
  },
  {
    id: "rag-eval",
    category: "Evaluation",
    question: "How do you evaluate a RAG system?",
    answer: "Separate the pipeline. Evaluate retrieval with hit/recall@k and ranking metrics against expected evidence. Evaluate generation for correctness, faithfulness, citation support, relevance and abstention. Add end-to-end task success, latency and cost. Use a representative golden set, slices and human review; treat LLM judges as noisy instruments.",
    signals: ["Retrieval vs generation", "Golden set", "Slices", "Human calibration"],
    trap: "Reporting only answer similarity or one aggregate score, which hides retrieval failures.",
    followUp: "How would you diagnose a fluent wrong answer with correct documents retrieved?",
    priority: "Core",
  },
  {
    id: "prompt-regression",
    category: "Evaluation",
    question: "How do you safely ship a prompt change?",
    answer: "Version the prompt and run it on a frozen representative eval set. Compare quality, safety, latency and token cost by slice; inspect regressions, then canary a small share of production traffic with traceability and a rollback path. Online A/B tests measure user impact after offline gates pass.",
    signals: ["Versioning", "Frozen eval set", "Slice regressions", "Canary + rollback"],
    trap: "Judging a change from a handful of hand-picked examples.",
    followUp: "What data would you log so a bad answer can be reproduced?",
    priority: "Core",
  },
  {
    id: "injection",
    category: "Evaluation",
    question: "How do you defend against prompt injection in RAG?",
    answer: "Treat retrieved text and tool outputs as untrusted data, not instructions. Separate system policy from content, restrict tools with least privilege, validate arguments, require confirmation for high-impact actions, filter results by authorization before generation and test adversarial cases. Detection helps, but the security boundary must not depend on the model obeying.",
    signals: ["Untrusted content", "Least privilege", "Authorization outside model", "Adversarial evals"],
    trap: "Relying on a prompt that says ‘ignore malicious instructions.’",
    followUp: "What changes when the assistant can only answer versus take actions?",
    priority: "Core",
  },
  {
    id: "lambda-sagemaker",
    category: "Cloud + MLOps",
    question: "SageMaker endpoint vs Lambda for inference: how do you decide?",
    answer: "Lambda is good for short, stateless orchestration with strict runtime, package and memory limits. A managed model endpoint fits heavier artifacts, specialized containers, accelerators, predictable throughput and model-centric deployment controls. A common design uses API Gateway and Lambda for auth/validation, then SageMaker for inference.",
    signals: ["Workload constraints", "Orchestration vs serving", "Scaling", "Operational tradeoff"],
    trap: "Choosing by product name rather than latency, payload, model size and traffic shape.",
    followUp: "How would you handle cold starts and a sudden traffic spike?",
    priority: "Build",
  },
  {
    id: "ml-cicd",
    category: "Cloud + MLOps",
    question: "Design CI/CD and rollback for an ML model.",
    answer: "Version code, data lineage, features, model artifact and evaluation report. CI validates contracts and reproducibility; CD promotes an immutable candidate through offline gates, shadow/canary traffic and monitored rollout. Keep the previous model and feature contract deployable, define rollback triggers, and separate model approval from application release where needed.",
    signals: ["Full lineage", "Immutable artifact", "Canary", "Rollback contract"],
    trap: "Treating a model like ordinary code while ignoring data and statistical validation.",
    followUp: "What makes a rollback unsafe when feature pipelines have also changed?",
    priority: "Build",
  },
  {
    id: "recommendation",
    category: "System design",
    question: "Design a recommendation system.",
    answer: "Clarify objective and constraints; define events and labels. Use broad candidate generation followed by a richer ranking model, then business-rule and diversity filters. Separate offline training from low-latency serving, keep online/offline features consistent, log exposure for unbiased evaluation, and monitor quality, latency, drift and feedback loops.",
    signals: ["Objective", "Candidates → ranking", "Feature consistency", "Exposure logging"],
    trap: "Jumping to a model before defining success, feedback bias and serving constraints.",
    followUp: "How would you solve cold start for new users and new items?",
    priority: "Core",
  },
  {
    id: "enterprise-rag",
    category: "System design",
    question: "Design an enterprise RAG platform.",
    answer: "Start with users, sources, freshness and permission requirements. Build source-specific ingestion into parsed, versioned chunks with metadata and ACLs; create hybrid retrieval with authorization filtering and optional reranking; assemble grounded prompts through an LLM gateway; validate citations and outputs; then add evals, traces, cost controls, deletion/refresh workflows and failure fallbacks.",
    signals: ["Requirements first", "ACL-aware ingestion/retrieval", "Gateway", "Eval + operations"],
    trap: "Drawing vector DB → LLM and omitting tenancy, refresh, deletion, evaluation and failure modes.",
    followUp: "How do you prevent a user from inferring that a restricted document exists?",
    priority: "Core",
  },
  {
    id: "llm-gateway",
    category: "System design",
    question: "What belongs in an LLM gateway?",
    answer: "A gateway centralizes provider abstraction, model routing, authentication, policy, quotas, prompt/model versions, retries and fallbacks, redaction, telemetry and cost controls. It should not hide every provider difference or become a monolith; preserve typed capability contracts and let applications own domain behavior and final authorization.",
    signals: ["Cross-cutting policy", "Routing", "Observability", "Typed capabilities"],
    trap: "Putting business logic in the gateway or assuming all providers are interchangeable.",
    followUp: "How would you route requests across models without silently changing quality?",
    priority: "Build",
  },
  {
    id: "agent-tools",
    category: "System design",
    question: "Design an AI agent that calls internal APIs safely.",
    answer: "Expose a small typed tool set behind ordinary authorization. The model proposes a plan and arguments; deterministic code validates identity, permissions, schemas, rate limits and preconditions. Separate read from write tools, require confirmation for consequential actions, make writes idempotent, cap loops and budgets, and trace every decision and tool result.",
    signals: ["Model proposes", "Code authorizes", "Confirmation", "Idempotency + limits"],
    trap: "Granting broad API credentials to the model or letting natural language define permissions.",
    followUp: "How would you recover after the tool succeeds but the agent times out?",
    priority: "Build",
  },
  {
    id: "lora",
    category: "Advanced LLM",
    question: "Explain LoRA and QLoRA.",
    answer: "LoRA freezes the base model and learns small low-rank update matrices for selected weights, reducing trainable parameters and memory. QLoRA also stores the frozen base in low precision while training LoRA adapters, reducing memory further. They lower adaptation cost, but data quality, evaluation and serving complexity still matter.",
    signals: ["Frozen base", "Low-rank adapters", "Quantized base", "Operational tradeoff"],
    trap: "Claiming LoRA is equivalent to full fine-tuning or always matches its quality.",
    followUp: "When would RAG still be necessary after LoRA tuning?",
    priority: "Advanced",
  },
  {
    id: "quantization",
    category: "Advanced LLM",
    question: "What is quantization, and what can go wrong?",
    answer: "Quantization represents weights—and sometimes activations or KV cache—with fewer bits to reduce memory bandwidth, footprint and often latency. Accuracy can degrade, especially for sensitive layers or tasks; hardware kernels and calibration matter. Evaluate task quality and throughput on the actual serving stack rather than assuming lower bits are faster.",
    signals: ["Lower precision", "Memory bandwidth", "Quality risk", "Hardware-specific benchmark"],
    trap: "Equating model size reduction with guaranteed end-to-end speedup.",
    followUp: "What is the difference between post-training quantization and quantization-aware training?",
    priority: "Advanced",
  },
  {
    id: "kv-cache",
    category: "Advanced LLM",
    question: "What is the KV cache, and why does it matter for inference?",
    answer: "During autoregressive decoding, attention needs keys and values from previous tokens. Caching them avoids recomputing the whole prefix for every new token, greatly reducing decode work. The cache grows with sequence length, batch size, layers and hidden dimensions, so it becomes a major memory and concurrency constraint.",
    signals: ["Autoregressive decode", "Reuse K/V", "Latency", "Memory/concurrency"],
    trap: "Saying it caches answers or eliminates the quadratic prefill cost.",
    followUp: "Why can batching improve throughput while hurting latency?",
    priority: "Advanced",
  },
  {
    id: "why-ai-transition",
    category: "Positioning",
    question: "Why are you moving from data engineering into AI / LLM engineering?",
    answer: "Frame the move as an extension of your engineering strengths, not an escape from your current field. Connect reliable data systems to the next layer: models, retrieval, evaluation and AI products. Use one concrete project that changed your scope, then explain why the target role lets you create more value with both skill sets.",
    signals: ["Coherent transition", "Transferable strengths", "Project evidence", "Forward-looking fit"],
    trap: "Saying AI is exciting or popular without showing sustained work and relevant evidence.",
    followUp: "Which parts of data engineering remain most important in production AI systems?",
    priority: "Core",
  },
  {
    id: "behavior-difficult-project",
    category: "Positioning",
    question: "Tell me about a difficult project and how you handled it.",
    answer: "Use a concise STAR structure, but spend most time on your decisions. Define why the situation was difficult, your specific responsibility, the options you considered, what you did, and a measurable result. Close with what you learned and what you would change now.",
    signals: ["Specific difficulty", "Your decisions", "Measured result", "Reflection"],
    trap: "Describing team activity without making your own contribution or judgment visible.",
    followUp: "What was the hardest tradeoff, and who disagreed with your approach?",
    priority: "Core",
  },
  {
    id: "behavior-incident",
    category: "Positioning",
    question: "Tell me about a production incident you handled.",
    answer: "Explain impact and detection first, then containment, diagnosis, recovery and prevention. Show calm prioritization, clear communication and evidence-based debugging. Distinguish the immediate fix from the systemic corrective action, and be explicit about your role and the resulting reliability improvement.",
    signals: ["Impact", "Containment", "Root cause", "Prevention"],
    trap: "Turning the story into blame or hiding the operational and customer impact.",
    followUp: "What signal would have detected the problem earlier?",
    priority: "Core",
  },
  {
    id: "behavior-mistake",
    category: "Positioning",
    question: "Tell me about a mistake you made.",
    answer: "Choose a real, consequential but recoverable mistake. Own it without excuses, explain how you discovered and corrected it, and show the durable process or technical change that prevented recurrence. A strong answer demonstrates judgment growth rather than presenting a disguised strength.",
    signals: ["Real ownership", "Correction", "Prevention", "Changed behavior"],
    trap: "Using a harmless perfectionism story or blaming unclear requirements.",
    followUp: "How did you rebuild trust with the people affected?",
    priority: "Core",
  },
  {
    id: "behavior-leadership",
    category: "Positioning",
    question: "Tell me about a time you led without formal authority.",
    answer: "Define the shared problem, the stakeholders and why alignment was difficult. Show how you built credibility with evidence, listened to constraints, created a practical path and helped others succeed. Leadership is demonstrated by movement and durable adoption, not by doing all the work yourself.",
    signals: ["Influence", "Stakeholder empathy", "Shared plan", "Adoption"],
    trap: "Equating leadership with taking over or simply scheduling meetings.",
    followUp: "What did you do when an important stakeholder still disagreed?",
    priority: "Build",
  },
  {
    id: "python-collections",
    category: "Python + SQL",
    question: "Compare Python list, tuple and set. When would you use each?",
    answer: "A list is ordered and mutable, suited to sequences that change. A tuple is ordered and immutable, useful for fixed records and potentially hashable keys when all elements are hashable. A set stores unique hashable values and gives average O(1) membership tests, but it is not a positional sequence.",
    signals: ["Mutability", "Ordering", "Uniqueness", "Complexity"],
    trap: "Claiming a set is sorted or that every tuple is hashable.",
    followUp: "Why might set membership be much faster than list membership?",
    priority: "Core",
  },
  {
    id: "python-decorator",
    category: "Python + SQL",
    question: "What is a decorator, and where is it useful?",
    answer: "A decorator is a callable that receives another function or class and returns a wrapped or modified callable. It separates cross-cutting behavior such as logging, authorization, caching or timing from business logic. Use functools.wraps to preserve metadata and avoid hiding control flow behind excessive decoration.",
    signals: ["Higher-order callable", "Wrapping", "Cross-cutting behavior", "functools.wraps"],
    trap: "Only showing @ syntax without explaining the function transformation.",
    followUp: "How would you write a decorator that accepts its own arguments?",
    priority: "Core",
  },
  {
    id: "python-context-manager",
    category: "Python + SQL",
    question: "What is a context manager, and why use one?",
    answer: "A context manager defines setup and guaranteed cleanup around a block through __enter__ and __exit__, or contextlib. It is ideal for files, locks, transactions and temporary resources because cleanup runs even when the body raises. It manages lifetime; it should not silently suppress errors unless that is intentional.",
    signals: ["Setup/cleanup", "with statement", "Exception safety", "Resource lifetime"],
    trap: "Saying it is only a shorter syntax for opening files.",
    followUp: "When should __exit__ return True?",
    priority: "Core",
  },
  {
    id: "python-gil",
    category: "Python + SQL",
    question: "What is Python's GIL, and how does it affect concurrency?",
    answer: "In standard CPython, the Global Interpreter Lock allows one thread to execute Python bytecode at a time. Threads can still help I/O-bound work because the lock is released while waiting, but CPU-bound Python often needs multiprocessing, native extensions or another runtime strategy. The GIL does not make application code automatically thread-safe.",
    signals: ["CPython bytecode", "I/O vs CPU", "Multiprocessing", "Not thread safety"],
    trap: "Claiming Python cannot run concurrent work or that threads are always useless.",
    followUp: "How would you choose between threading, asyncio and multiprocessing?",
    priority: "Build",
  },
  {
    id: "python-async",
    category: "Python + SQL",
    question: "When is asyncio appropriate, and when is it not?",
    answer: "Asyncio is useful for high-concurrency I/O when libraries expose non-blocking APIs. A single event loop cooperatively switches at await points, reducing per-request thread overhead. It does not accelerate CPU-heavy work, and one blocking call can stall the loop, so use executors or separate workers for blocking and CPU-bound tasks.",
    signals: ["I/O concurrency", "Event loop", "Cooperative scheduling", "Blocking risk"],
    trap: "Treating async as automatic parallelism or adding it to a low-concurrency program without need.",
    followUp: "What happens if a synchronous model call runs inside an async endpoint?",
    priority: "Build",
  },
  {
    id: "python-group-anagrams",
    category: "Python + SQL",
    question: "How would you group anagrams efficiently?",
    answer: "Create a canonical key for each word and group words in a dictionary. Sorting characters gives O(k log k) per word and is simple; a fixed-size character-frequency tuple gives O(k) for a known alphabet. State assumptions about case, Unicode and normalization before choosing the key.",
    signals: ["Canonical key", "Dictionary grouping", "Complexity", "Input assumptions"],
    trap: "Comparing every pair of words, which becomes quadratic in the number of words.",
    followUp: "How would Unicode or a very large alphabet change your approach?",
    priority: "Core",
  },
  {
    id: "sql-joins",
    category: "Python + SQL",
    question: "Explain INNER, LEFT, RIGHT and FULL joins.",
    answer: "An INNER join keeps matched rows from both sides. A LEFT join keeps every left row and fills unmatched right columns with NULL; RIGHT is the mirror image. FULL keeps unmatched rows from both sides. Always reason about key cardinality because many-to-many matches can multiply rows unexpectedly.",
    signals: ["Matched rows", "Preserved side", "NULL padding", "Cardinality"],
    trap: "Explaining joins only with Venn diagrams and ignoring duplicate keys.",
    followUp: "How would you detect an unintended row explosion after a join?",
    priority: "Core",
  },
  {
    id: "sql-null",
    category: "Python + SQL",
    question: "How does NULL behave in SQL?",
    answer: "NULL represents unknown or missing, so comparisons use three-valued logic. NULL = NULL is not true; use IS NULL. Aggregates usually ignore NULL except COUNT(*), while joins and NOT IN can behave unexpectedly. Use COALESCE only when replacing unknown with a real business default is semantically correct.",
    signals: ["Unknown", "Three-valued logic", "IS NULL", "Aggregate behavior"],
    trap: "Treating NULL as zero or an empty string.",
    followUp: "Why can NOT IN return no rows when its subquery contains NULL?",
    priority: "Core",
  },
  {
    id: "sql-rolling-average",
    category: "Python + SQL",
    question: "How do you calculate a rolling 7-day average in SQL?",
    answer: "First define whether seven days means seven calendar dates or seven observed rows. After filling missing dates when necessary, use AVG(value) OVER with an ordered window such as ROWS BETWEEN 6 PRECEDING AND CURRENT ROW. Partition by the entity and make the ordering deterministic.",
    signals: ["Calendar vs rows", "Window function", "Partition", "Missing dates"],
    trap: "Using six preceding rows when dates are sparse and calling it a seven-day window.",
    followUp: "How would you handle multiple events per day before computing the average?",
    priority: "Core",
  },
  {
    id: "ml-bias-variance",
    category: "ML fundamentals",
    question: "Explain the bias–variance tradeoff.",
    answer: "Bias is systematic error from assumptions that are too simple; variance is sensitivity to the particular training sample. Increasing model flexibility often reduces bias but raises variance. Diagnose with learning curves and train/validation behavior, then adjust data, features, regularization or model capacity rather than blindly choosing a more complex model.",
    signals: ["Underfit vs sensitivity", "Generalization", "Learning curves", "Targeted remedy"],
    trap: "Treating bias and variance as direct metrics that always sum to one fixed amount.",
    followUp: "What pattern in training and validation error suggests high variance?",
    priority: "Core",
  },
  {
    id: "ml-l1-l2",
    category: "ML fundamentals",
    question: "Compare L1 and L2 regularization.",
    answer: "L1 adds the absolute value of weights and can drive coefficients exactly to zero, which encourages sparsity. L2 adds squared weights and smoothly shrinks them, often distributing weight across correlated features. Both trade training fit for stability; standardize feature scales and tune strength on validation data.",
    signals: ["Absolute vs squared", "Sparsity", "Correlated features", "Scale"],
    trap: "Calling L1 a universally reliable feature-selection method.",
    followUp: "What is elastic net, and when could it help?",
    priority: "Core",
  },
  {
    id: "ml-random-forest",
    category: "ML fundamentals",
    question: "How does a Random Forest work?",
    answer: "A Random Forest trains many decision trees on bootstrap samples while considering random feature subsets at each split. Averaging reduces the variance of individual trees, especially when trees are decorrelated. It handles nonlinear interactions well but can be large, less interpretable and weak at extrapolation.",
    signals: ["Bagging", "Feature randomness", "Variance reduction", "Tradeoffs"],
    trap: "Saying more trees fix every form of overfitting or leakage.",
    followUp: "What is out-of-bag evaluation?",
    priority: "Core",
  },
  {
    id: "ml-boosting",
    category: "ML fundamentals",
    question: "Explain gradient boosting and why it often performs well on tabular data.",
    answer: "Gradient boosting adds weak trees sequentially, each fitting residual-like gradients of the loss from the current ensemble. Learning rate, depth, number of trees and sampling control the bias–variance tradeoff. It captures nonlinearities and interactions effectively, but requires careful validation and can overfit leakage or noisy targets.",
    signals: ["Sequential ensemble", "Loss gradients", "Shrinkage", "Validation"],
    trap: "Describing boosting as independent trees like a Random Forest.",
    followUp: "How do learning rate and number of trees interact?",
    priority: "Core",
  },
  {
    id: "ml-cross-validation",
    category: "ML fundamentals",
    question: "When should you not use ordinary random k-fold cross-validation?",
    answer: "Random folds are unsafe when observations are time-dependent, grouped, duplicated or otherwise able to leak across folds. Use time-based splits for forecasting, group splits for users or patients, and purge overlapping windows when labels use future intervals. The split must simulate how the model will face unseen data.",
    signals: ["Deployment simulation", "Time", "Groups", "Leakage prevention"],
    trap: "Choosing k-fold mechanically because it produces a stable average score.",
    followUp: "How would you validate an AML model when customer histories span years?",
    priority: "Core",
  },
  {
    id: "ml-calibration",
    category: "ML fundamentals",
    question: "What is probability calibration, and why does it matter?",
    answer: "A model is calibrated when events assigned probability p occur about p percent of the time within relevant groups. Ranking metrics such as AUC do not guarantee calibration. Use reliability plots and proper scoring rules, then calibrate on held-out data with methods such as Platt scaling or isotonic regression.",
    signals: ["Probability meaning", "AUC distinction", "Reliability plot", "Held-out calibration"],
    trap: "Evaluating calibration on the same data used to fit the calibrator.",
    followUp: "Can a model be well calibrated but poor at ranking?",
    priority: "Build",
  },
  {
    id: "ml-imbalance",
    category: "ML fundamentals",
    question: "How do you handle severely imbalanced classification data?",
    answer: "Start with the decision and error costs, then choose precision/recall-oriented metrics and thresholding. Consider class weights, careful resampling, suitable losses and better signal collection, but keep validation at natural prevalence. Evaluate calibration and cohort performance because oversampling changes the apparent class distribution.",
    signals: ["Business cost", "Right metrics", "Natural-prevalence test", "Threshold"],
    trap: "Using accuracy or automatically applying SMOTE before understanding the data geometry.",
    followUp: "When can synthetic minority oversampling make performance worse?",
    priority: "Core",
  },
  {
    id: "ml-data-concept-drift",
    category: "ML fundamentals",
    question: "What is the difference between data drift and concept drift?",
    answer: "Data drift means the input distribution P(X) changes. Concept drift means the relationship between inputs and target P(Y|X) changes. Input drift is observable without labels but may be harmless; concept drift directly threatens predictions but usually needs outcomes or strong proxies. Diagnose by feature, segment and time before acting.",
    signals: ["P(X)", "P(Y|X)", "Labels", "Segment diagnosis"],
    trap: "Retraining automatically whenever one feature distribution changes.",
    followUp: "How could you detect concept drift when labels arrive months later?",
    priority: "Core",
  },
  {
    id: "ml-explainability",
    category: "ML fundamentals",
    question: "How would you explain an AML risk model to regulators and investigators?",
    answer: "Separate global model behavior from an individual decision. Document data lineage, intended use, validation and limitations; provide stable reason codes or local explanations that investigators can verify; test consistency and protected-group impacts. Explanations must reflect the actual model and support governance, not merely look intuitive.",
    signals: ["Global vs local", "Lineage", "Reason codes", "Governance"],
    trap: "Treating SHAP values as causal explanations or proof of fairness.",
    followUp: "How would you test whether explanations are stable enough for operations?",
    priority: "Build",
  },
  {
    id: "llm-tokenization",
    category: "LLM core",
    question: "What is tokenization, and why does it matter in LLM applications?",
    answer: "Tokenization converts text into model vocabulary IDs, often using subword units. Token boundaries do not equal words and vary by model, language and content. Tokenization affects context limits, cost, latency, chunking and exact-string tasks, so estimate with the target model's tokenizer rather than character counts.",
    signals: ["Subword IDs", "Model-specific", "Cost/context", "Language effects"],
    trap: "Assuming one token equals one word or that all providers tokenize identically.",
    followUp: "Why might code or non-English text consume unexpectedly many tokens?",
    priority: "Core",
  },
  {
    id: "llm-context-window",
    category: "LLM core",
    question: "What is a context window, and why not always fill it?",
    answer: "The context window is the maximum token budget covering instructions, input, retrieved evidence and generated output. Longer context raises cost and latency and can dilute attention or bury relevant evidence. Select and organize only useful information, reserve output capacity and evaluate long-context behavior instead of treating capacity as guaranteed effective memory.",
    signals: ["Shared token budget", "Latency/cost", "Relevance dilution", "Output reserve"],
    trap: "Equating advertised context length with perfect recall across the entire prompt.",
    followUp: "How would you handle a document larger than the context window?",
    priority: "Core",
  },
  {
    id: "llm-transformer",
    category: "LLM core",
    question: "What is a Transformer at a high level?",
    answer: "A Transformer processes token representations through repeated attention and feed-forward blocks with residual connections and normalization. Attention mixes information across positions, while feed-forward layers transform each position. Decoder-only LLMs use causal masking so each token predicts from prior context during autoregressive generation.",
    signals: ["Attention", "Feed-forward", "Residuals", "Causal mask"],
    trap: "Saying a Transformer is simply attention without mentioning the rest of the block or training objective.",
    followUp: "What differs between encoder-only and decoder-only models?",
    priority: "Core",
  },
  {
    id: "llm-prompt-hierarchy",
    category: "LLM core",
    question: "What is the role of system, developer and user instructions?",
    answer: "Instruction layers communicate policy and task context with different authority. Higher-priority instructions constrain lower-priority requests, while retrieved documents and tool output should be treated as data. Applications should keep durable policy separate from user content and enforce real security controls outside the prompt.",
    signals: ["Instruction hierarchy", "Policy separation", "Untrusted data", "External enforcement"],
    trap: "Assuming instruction hierarchy is a complete security boundary against prompt injection.",
    followUp: "Where should user-specific authorization be enforced?",
    priority: "Core",
  },
  {
    id: "llm-few-shot",
    category: "LLM core",
    question: "When does few-shot prompting help, and what can go wrong?",
    answer: "Few-shot examples clarify ambiguous formats, decision boundaries and style without changing model weights. Use representative, diverse examples with correct labels and avoid leaking the answer. Examples consume context and can bias the model toward their wording or distribution, so test performance by slice against a zero-shot baseline.",
    signals: ["Demonstration", "Representative examples", "Context cost", "Evaluation"],
    trap: "Selecting only easy examples that make the prompt look better in demos.",
    followUp: "How would you choose examples for a rare but important edge case?",
    priority: "Build",
  },
  {
    id: "llm-json-validation",
    category: "LLM core",
    question: "How do you handle invalid or unsafe structured output from an LLM?",
    answer: "Use schema-constrained generation when available, then parse and validate types, ranges, enums and business invariants in deterministic code. Reject or repair only narrowly, retry with bounded attempts, and log validation failures. Never execute a tool or persist data merely because the JSON is syntactically valid.",
    signals: ["Schema constraint", "Deterministic validation", "Bounded retry", "Business invariants"],
    trap: "Using regex cleanup as the primary safety mechanism or trusting valid JSON as valid intent.",
    followUp: "Which validation errors are safe to retry automatically?",
    priority: "Core",
  },
  {
    id: "llm-temperature",
    category: "LLM core",
    question: "What does temperature control, and when should it be low?",
    answer: "Temperature rescales token logits before sampling, changing how peaked or diverse the output distribution is. Lower values improve repeatability for extraction, classification and tool arguments; higher values may help ideation. It does not make facts more reliable, and some provider settings or constrained decoders limit its effect.",
    signals: ["Logit scaling", "Randomness", "Task fit", "Not factuality"],
    trap: "Claiming temperature zero guarantees identical or hallucination-free answers.",
    followUp: "What other sources of nondeterminism can remain at temperature zero?",
    priority: "Build",
  },
  {
    id: "rag-metadata",
    category: "RAG",
    question: "What metadata should a RAG system store with each chunk?",
    answer: "Store stable document and chunk IDs, source and location, title/section, version, timestamps, content type, language, tenant and access-control attributes. Metadata must support filtering, citations, refresh and deletion. Avoid copying sensitive fields unless required, and keep authorization attributes synchronized with the source.",
    signals: ["Identity", "Provenance", "ACLs", "Lifecycle"],
    trap: "Storing only raw text and an embedding, making refresh and trustworthy citations impossible.",
    followUp: "How would you update metadata when source permissions change?",
    priority: "Core",
  },
  {
    id: "rag-vector-failure",
    category: "RAG",
    question: "Why can vector search return bad results?",
    answer: "The embedding may not represent the domain or query intent, chunks may be poorly formed, nearest neighbors may be semantically related but not answer-bearing, and approximate search can miss candidates. Diagnose ingestion, query formulation, metadata filters and recall separately before changing the vector database.",
    signals: ["Embedding fit", "Chunk quality", "Answer-bearing evidence", "Recall diagnosis"],
    trap: "Assuming vector similarity equals relevance or blaming the database first.",
    followUp: "How would you tell whether the problem is the embedding model or chunking?",
    priority: "Core",
  },
  {
    id: "rag-access-control",
    category: "RAG",
    question: "How do you enforce document-level permissions in RAG?",
    answer: "Carry source ACLs into indexed metadata and filter candidates using the authenticated user's effective permissions before content reaches the model. Revalidate when needed, handle permission changes and deletion, isolate tenants and test side channels. The model must never decide whether a user may see a document.",
    signals: ["ACL propagation", "Pre-generation filtering", "Tenant isolation", "Permission lifecycle"],
    trap: "Retrieving restricted text and asking the prompt not to reveal it.",
    followUp: "How do you prevent leakage through logs, caches or citations?",
    priority: "Core",
  },
  {
    id: "rag-citations",
    category: "RAG",
    question: "How do you produce trustworthy citations in a RAG answer?",
    answer: "Give the model stable source markers tied to retrieved chunks, require claim-level attribution, then validate that cited sources were retrieved and actually support the claim. Render links from trusted metadata rather than model-generated URLs. Measure citation correctness and completeness, not just whether citations appear.",
    signals: ["Stable source IDs", "Claim support", "Trusted URLs", "Citation metrics"],
    trap: "Treating a citation marker as proof that the source entails the statement.",
    followUp: "How would you handle an answer supported by several conflicting documents?",
    priority: "Core",
  },
  {
    id: "rag-refresh",
    category: "RAG",
    question: "How do you refresh and delete documents in a production RAG index?",
    answer: "Use stable source IDs, content hashes and versions so ingestion can upsert changed chunks and delete superseded ones idempotently. Track source-to-chunk lineage, process deletion and permission events promptly, and reconcile periodically against the source of truth. Avoid blind full re-indexing when incremental updates are sufficient.",
    signals: ["Stable IDs", "Versioning", "Idempotent upsert", "Reconciliation"],
    trap: "Appending every update and leaving stale or revoked chunks retrievable.",
    followUp: "How would you make a failed partial refresh safe to retry?",
    priority: "Build",
  },
  {
    id: "rag-multihop",
    category: "RAG",
    question: "How would you handle a question that requires evidence from multiple documents?",
    answer: "Detect that one retrieval pass is insufficient, decompose the question into bounded subqueries, retrieve evidence for each, and synthesize only after preserving provenance. Limit iterations and avoid letting early model assumptions steer all later searches. Evaluate both evidence coverage and final claim support.",
    signals: ["Decomposition", "Bounded retrieval", "Provenance", "Coverage evaluation"],
    trap: "Using an unconstrained agent loop that compounds an incorrect first assumption.",
    followUp: "When is query decomposition unnecessary or harmful?",
    priority: "Build",
  },
  {
    id: "rag-abstention",
    category: "RAG",
    question: "How should a RAG system decide when not to answer?",
    answer: "Define abstention behavior using retrieval evidence, source coverage and task risk rather than a single similarity threshold. Train or prompt for explicit insufficiency, require citations for material claims and evaluate answerability on known unanswerable questions. Route high-risk uncertainty to search, clarification or a human.",
    signals: ["Evidence sufficiency", "Risk", "Unanswerable evals", "Fallback"],
    trap: "Assuming the model's stated confidence is a calibrated probability of correctness.",
    followUp: "How would you tune abstention without making the assistant useless?",
    priority: "Build",
  },
  {
    id: "eval-faithfulness",
    category: "Evaluation",
    question: "What is faithfulness, and how is it different from correctness?",
    answer: "Faithfulness asks whether claims are supported by the provided evidence. Correctness asks whether the answer is true relative to the task's ground truth. An answer can be correct but unsupported by retrieved documents, or faithful to a source that is outdated. Production evaluation needs both when grounding matters.",
    signals: ["Evidence support", "Ground truth", "Two failure modes", "Grounded tasks"],
    trap: "Using faithfulness as a synonym for factual accuracy.",
    followUp: "How would you evaluate faithfulness at the individual-claim level?",
    priority: "Core",
  },
  {
    id: "eval-llm-judge",
    category: "Evaluation",
    question: "What are the strengths and risks of LLM-as-judge evaluation?",
    answer: "LLM judges scale qualitative grading and can apply detailed rubrics, but they have position, verbosity, self-preference and domain biases. Calibrate against blinded human labels, randomize order, require structured rationales, track agreement by slice and never use one judge as unquestioned ground truth.",
    signals: ["Scalable rubric", "Known biases", "Human calibration", "Slice agreement"],
    trap: "Reporting judge scores without validating that the judge recognizes important failures.",
    followUp: "How would you compare two prompts while reducing position bias?",
    priority: "Core",
  },
  {
    id: "eval-tracing",
    category: "Evaluation",
    question: "What should an LLM request trace contain?",
    answer: "Record a request ID, application and prompt/model versions, retrieval query and source IDs, tool calls, validation outcomes, timing, token/cost data and final status. Protect or redact user content and secrets, preserve parent-child spans and retention policy, and make traces reproducible without turning logs into a privacy leak.",
    signals: ["Versions", "Retrieval/tools", "Latency/cost", "Privacy"],
    trap: "Logging full prompts, documents and credentials by default.",
    followUp: "How would you debug one bad answer from only its request ID?",
    priority: "Core",
  },
  {
    id: "eval-cost",
    category: "Evaluation",
    question: "How do you monitor and reduce LLM cost without silently reducing quality?",
    answer: "Attribute input/output tokens and provider charges by feature, tenant and request type, then track cost per successful task alongside quality and latency. Reduce waste through better retrieval, shorter prompts, caching, routing and output limits. Gate every optimization with the same evaluation slices used for quality releases.",
    signals: ["Unit economics", "Attribution", "Quality guardrail", "Targeted optimization"],
    trap: "Optimizing price per token while ignoring retries, failures and user task completion.",
    followUp: "When is semantic caching unsafe?",
    priority: "Build",
  },
  {
    id: "eval-pii-logging",
    category: "Evaluation",
    question: "How do you keep observability useful without leaking PII or secrets?",
    answer: "Classify data, minimize what is collected, redact or tokenize sensitive fields before durable logging, restrict access and retention, and separate operational metadata from protected content. Provide sampled secure replay only when justified, audit access and test redaction against realistic formats and encoded secrets.",
    signals: ["Data minimization", "Redaction", "Access/retention", "Secure replay"],
    trap: "Assuming an instruction to the model not to repeat PII protects logs.",
    followUp: "What would you log when raw prompts cannot be retained at all?",
    priority: "Core",
  },
  {
    id: "cloud-cold-start",
    category: "Cloud + MLOps",
    question: "What causes cold starts, and how do you manage them?",
    answer: "Cold starts occur when a platform provisions a new runtime and loads code, dependencies or model artifacts before serving. Measure each phase, reduce artifact and initialization work, reuse clients, keep warm or provision capacity for strict latency, and use queues or asynchronous paths where users need not wait synchronously.",
    signals: ["Provisioning", "Initialization", "Measurement", "Capacity tradeoff"],
    trap: "Promising to eliminate cold starts without acknowledging cost and traffic patterns.",
    followUp: "How would you decide whether provisioned concurrency is worth the cost?",
    priority: "Build",
  },
  {
    id: "cloud-request-tracing",
    category: "Cloud + MLOps",
    question: "How would you trace a request across API Gateway, Lambda and SageMaker?",
    answer: "Generate or accept a correlation ID at the edge, propagate it through structured logs, tracing headers and inference metadata, and create spans for authorization, preprocessing, endpoint invocation and postprocessing. Centralize searchable traces, record model/version IDs and avoid logging payload secrets.",
    signals: ["Correlation ID", "Propagation", "Spans", "Model version"],
    trap: "Using independent log timestamps and expecting operators to reconstruct every request manually.",
    followUp: "How would you trace retries without counting them as separate user requests?",
    priority: "Core",
  },
  {
    id: "cloud-secrets",
    category: "Cloud + MLOps",
    question: "How should an AI service store and use secrets?",
    answer: "Store secrets in a managed secret service, grant narrowly scoped runtime identities permission to fetch only what they need, rotate credentials and cache them only within safe lifetime rules. Never bake keys into images, source or prompts; redact headers and errors and prefer short-lived identity-based credentials where supported.",
    signals: ["Managed store", "Least privilege", "Rotation", "No prompt/log exposure"],
    trap: "Putting a secret in an environment file committed to source control.",
    followUp: "How would you rotate a provider API key without downtime?",
    priority: "Core",
  },
  {
    id: "cloud-endpoint-deploy",
    category: "Cloud + MLOps",
    question: "How do you deploy and monitor a SageMaker model endpoint?",
    answer: "Package a reproducible model and inference container, define input/output contracts, deploy an immutable version behind an endpoint configuration and test with shadow or canary traffic. Monitor errors, latency, saturation, data quality and model outcomes; keep rollback configuration and artifact lineage available.",
    signals: ["Immutable artifact", "Contracts", "Canary", "Operational + model metrics"],
    trap: "Stopping at a successful health check without validating real payloads and outcome quality.",
    followUp: "What should happen when the endpoint is healthy but predictions drift?",
    priority: "Build",
  },
  {
    id: "cloud-serverless-inference",
    category: "Cloud + MLOps",
    question: "When is serverless inference a good fit?",
    answer: "Serverless inference fits intermittent or unpredictable traffic where paying for idle capacity is wasteful and the model fits platform limits. It trades lower idle cost for cold-start risk, less hardware control and throughput constraints. Benchmark real artifact load time, payload size and burst behavior against latency requirements.",
    signals: ["Traffic shape", "Idle cost", "Cold starts", "Platform limits"],
    trap: "Choosing serverless solely because average traffic is low.",
    followUp: "When would a real-time provisioned endpoint be safer?",
    priority: "Build",
  },
  {
    id: "design-fraud",
    category: "System design",
    question: "Design a real-time fraud detection system.",
    answer: "Clarify the decision, latency and false-positive cost. Ingest events, create point-in-time features, combine rules and a calibrated model, return a score plus action, and route uncertain cases to review. Log decisions and exposure, protect against leakage, monitor cohorts and drift, and design safe fallback behavior when features or models fail.",
    signals: ["Decision cost", "Online features", "Rules + model", "Fallback/review"],
    trap: "Optimizing AUC without defining the operational threshold, review capacity or adversarial adaptation.",
    followUp: "How would you avoid blocking legitimate users during an outage?",
    priority: "Core",
  },
  {
    id: "design-batch-scoring",
    category: "System design",
    question: "Design a reliable batch scoring pipeline.",
    answer: "Define schedule, freshness and delivery contract; build point-in-time feature snapshots; version data, code and model; partition idempotent scoring jobs; validate row counts and distributions; publish atomically with lineage. Add retries, backfills, late-data handling, quality gates and downstream reconciliation.",
    signals: ["Freshness contract", "Reproducibility", "Idempotency", "Atomic publish"],
    trap: "Treating batch as simple because it lacks an online latency requirement.",
    followUp: "How would you backfill six months without overwriting current results?",
    priority: "Build",
  },
  {
    id: "design-eval-platform",
    category: "System design",
    question: "Design an LLM evaluation platform.",
    answer: "Support versioned datasets, prompts, models and rubrics; run reproducible offline experiments; store per-example outputs, traces and metric provenance; compare by slice with human review queues; then connect release gates and production samples. Isolate sensitive data, control judge versions and make every aggregate score inspectable.",
    signals: ["Versioned artifacts", "Per-example evidence", "Slices", "Release gates"],
    trap: "Building a leaderboard of opaque aggregate scores with no reproducibility or drill-down.",
    followUp: "How would you prevent teams from overfitting to the shared evaluation set?",
    priority: "Build",
  },
  {
    id: "design-multi-provider",
    category: "System design",
    question: "Design multi-provider LLM routing and fallback.",
    answer: "Define typed capabilities and quality/latency/cost policies per task, then route only among providers that satisfy data residency, context and feature requirements. Use health-aware retries with idempotency, bounded fallback and consistent tracing. Evaluate each route and detect quality shifts; do not silently substitute an incompatible model.",
    signals: ["Capability contract", "Policy routing", "Bounded fallback", "Quality monitoring"],
    trap: "Reducing providers to one interchangeable chat API and ignoring semantic differences.",
    followUp: "How would you avoid duplicate tool actions during a provider timeout?",
    priority: "Build",
  },
  {
    id: "advanced-batching",
    category: "Advanced LLM",
    question: "How does batching affect LLM inference throughput and latency?",
    answer: "Batching lets requests share parallel accelerator work and usually improves throughput and utilization. Larger or continuously formed batches may increase queueing latency and waste work when sequence lengths differ. Dynamic or continuous batching balances arrivals, while service objectives and memory—not maximum batch size—should drive tuning.",
    signals: ["Utilization", "Queueing", "Sequence lengths", "Continuous batching"],
    trap: "Assuming the batch size with highest throughput also gives the best user experience.",
    followUp: "Why does padding waste become important for mixed sequence lengths?",
    priority: "Advanced",
  },
  {
    id: "advanced-vllm",
    category: "Advanced LLM",
    question: "What problem does vLLM solve at a high level?",
    answer: "vLLM is an inference-serving engine focused on high-throughput generation, notably through efficient KV-cache memory management and continuous batching. It exposes serving interfaces but does not choose the right model, guarantee quality or replace production capacity testing. Benchmark it on your hardware, sequence mix and latency objective.",
    signals: ["Inference engine", "KV-cache management", "Continuous batching", "Benchmarking"],
    trap: "Describing vLLM as a model or assuming its headline throughput applies to every workload.",
    followUp: "What workload characteristics would you include in a serving benchmark?",
    priority: "Advanced",
  },
];

export const cards = [
  ...coreCards,
  ...extraCards,
  ...dataEngineeringCards,
  ...codingCards,
  ...rapidFireCards,
  ...moxInterviewCards,
  ...moxPythonCards,
  ...hkexAwsBasicCards,
  ...hkexAwsAdvancedCards,
  ...hkexSqlIntermediateCards,
  ...hkexSqlAdvancedCards,
  ...hkexProblemSolvingBasicCards,
  ...hkexProblemSolvingAdvancedCards,
  ...hkexSyllabusAwsSqlCards,
  ...hkexSyllabusProblemSolvingCards,
  ...hkexInterviewCards,
  ...cmbiDataAgentCards,
] satisfies Card[];

export const readinessGate = [
  "Tell me about yourself.",
  "Why AI / LLM engineering?",
  "Explain your LLM platform architecture.",
  "What is RAG?",
  "Why RAG instead of fine-tuning?",
  "How do you evaluate a RAG system?",
  "How do you reduce hallucination?",
  "Explain your Scotiabank AML model.",
  "Design a document Q&A system.",
  "Design a recommendation / ranking system.",
];

export const projectStories = [
  {
    name: "Fleet enterprise LLM / RAG platform",
    proof: "Architecture, ingestion, retrieval, gateway, evaluation, security and observability.",
    structure: ["Why platform", "Architecture", "Retrieval", "Evaluation", "Security", "Tradeoffs"],
  },
  {
    name: "Scotiabank AML risk model",
    proof: "ML judgment under imbalance, explainability and regulatory constraints.",
    structure: ["Business risk", "Data", "Model choice", "Evaluation", "Explainability", "Impact"],
  },
  {
    name: "Crew recommendation on SageMaker",
    proof: "Production ranking, cloud boundaries, latency, monitoring and failure handling.",
    structure: ["Objective", "Why ranking", "Contracts", "Serving", "Monitoring", "Improvements"],
  },
];

export const cadence = [
  ["MON", "ML fundamentals", "5 answers out loud"],
  ["TUE", "LLM / RAG", "Notes + 5 answers"],
  ["WED", "Python + SQL", "1 coding + 1 SQL"],
  ["THU", "System design", "Draw + explain"],
  ["FRI", "Project deep dive", "1 story rehearsal"],
  ["SAT", "Mock interview", "60–90 minutes"],
  ["SUN", "Repair", "Rewrite weak answers"],
];

export const systemDesignFrames = {
  "ML system": [
    "Clarify requirements", "Users + objective", "Input / output", "Architecture", "Data + features",
    "Model choice", "Training", "Serving", "Monitoring", "Failures", "Tradeoffs", "Next step",
  ],
  "LLM system": [
    "Use case + users", "Permissions", "Sources", "Ingestion", "Chunking", "Retrieval", "Prompt assembly",
    "Gateway + tools", "Validation + citations", "Evaluation", "Monitoring", "Security", "Cost", "Failures",
  ],
};
